---
title: "Syllabus"
---

## Course Goals

-   Learn how to use modern regression methods to answer scientific questions
-   Become familiar with statistical concepts including exploratory data analysis, estimation, testing in linear, logistic, and survival models
-   Understand how the development of statistical methodology is motivated by biological and medical problems
-   Develop data analytic skills including familiarity with several statistical programs
-   Develop writing skills needed to communicate the results of a data analysis
-   Introduce reproducible research approaches using R, Rstudio, and Quarto

## Topics of Discussion

-   Bayesian and Frequentist approaches to fitting regression models
-   Linear regression
-   Logistic regression
-   Poisson regression
-   Survival models, primarily Cox Regression
-   Multinomial and ordinal logistic regression
-   Multivariable Regression
-   Matrix algebra and important results of random vectors
-   Precision, effect modification, and confounding
-   Specification issues in regression models
-   Model selection
-   Case Studies
-   Understanding model assumptions and the impact of assumptions on interpretation
-   Model Checking: diagnostics, transformations, influential observations, lack-of-fit test

## Course Description

### BIOS 6312

This is the second in a two-course series designed for students who seek to develop skills in modern biostatistical reasoning and data analysis. Students learn modern regression analysis and modeling building techniques from an applied perspective. Theoretical principles will be demonstrated with real-world examples from biomedical studies. This course requires substantial statistical computing in software packages and focuses on R; familiarity with R or proficiency in another high-level statistical program (e.g. Stata) is required. The course covers regression modeling for continuous outcomes, including simple linear regression, multiple linear regression, and analysis of variance with one-way, two-way, three-way, and analysis of covariance models. This is a brief introduction to models for binary outcomes (logistic models), ordinal outcomes (proportional odds models), count outcomes (Poisson/negative binomial models), and time to event outcomes (Kaplan-Meier curves, Cox proportional hazard modeling). Incorporated into the presentation of these models are subtopic topics such as regression diagnostics, nonparametric regression, splines, data reduction techniques, model validation, parametric bootstrapping, and a brief introduction to methods for handling missing data. Students are required to take 6312L concurrently. Prerequisite: Biostatistics 6311 or equivalent; familiarity with R or Stata software packages. SPRING.

### BIOS 6312L

This is a discussion section/lab for Modern Regression Analysis. Students will review relevant theory and work on applications as a group. Computing solutions and extensions will be emphasized. Students are required to take 6312 concurrently.

## Course Materials

### Course notes

-   Course notes will be the primary source
-   Available on web page
-   Daily class schedule will indicate notes being covered
-   Notes will be updated throughout semester

### Textbooks

-   There are no required textbooks for this course

-   The following are provided as references that are at an appropriate level for this course

    -   Regression Methods in Biostatistics. Vittinghoff, Glidden, Shiboski, and McCulloch

    -   Applied Liner Regression. Weisberg.

    -   Bayesian and Frequentist Regression Methods. Wakefield

## Grading and Evaluation

### Evaluation components and grade percentages

-   Midterm (25%)
-   Take Home Exam (25%)
-   Final Exam (25%)
-   Homework (25%)
-   Class participation
-   This is a 4-credit course. Your lab and lecture grades will be the same

### Homework

-   Up to 1 per week (probably 6 or 7 total)
-   Will focus on real data analysis and interpretation with some mathematical derivations of important quantities
-   Questions will focus on specific analyses, with questions stated in as scientific terms as possible
-   Work handed in should address the scientific questions
    -   Format Table and Figures
-   Keys will be provided shortly after the homework is turned in
    -   No late homework accepted after the key is posted
-   Answers in keys may go beyond what is expected of your homework and present concepts in more detail. You are responsible for any material in the keys for exams.
-   You may discuss the homework with others in the class, but the work you turn in should be your own
-   Use Brightspace to turn in homeworks and receive feedback and grade

### In Class Exams

-   Midterm and Final in class
    -   Focus on understanding concepts, not memorizing formulas
    -   I will provide an example midterm and final
    -   For midterm, you will be allowed 1 page of your own notes
    -   For final, you will be allowed 2 pages of your own notes
-   All output will be provide for you to interpret

### Take Home Exam

-   Will be given approximately mid point between Midterm and Final
-   Demonstrate ability to obtain results through software and interpret findings
-   One day to complete and turn in
    -   Likely will be a Monday with no lab scheduled for that day
-   Similar to Homework, but work must be your own

## Expectations and Policies

-   Expecations you can have of me

    -   You should expect me to provide feedback on homeworks and exams in a timely fashion

    -   You should expect me to be responsive to your questions and concerns. If you have emailed me and not received a response with 24 hours, please feel free to email again. It is best to use my VUMC rather than Vanderbilt email address.

-   Attendance. The course is offered in-person. If you expect to be absent, please let me know and make plans to catch up. Class will start on time.

-   Collaboration

    -   Discussing course content is highly encouraged

    -   Collaborating on homeworks is highly encouraged, but you need to turn in your own assignment written in your own words

    -   Exams (take home and in class) are individual effort

-   Academic honesty

    -   Students are expected to follow the Vanderbilt Honor Code

    -   "Vanderbilt University students pursue all academic endeavors with integrity. They conduct themselves honorably, professionally and respectfully in all realms of their studies in order to promote and secure an atmosphere of dignity and trust. The keystone of our honor system is self-regulation, which requires cooperation and support from each member of the University community."

-   Late work

    -   While I expect that work will be turned in on time, things can happen to interrupt your schedule

    -   My goal is to provide sufficient time for completing all assignments

    -   If you anticipate a problem with a due date, it is best to let me know sooner (e.g. when a homework is assigned) rather than later

    -   Late homeworks will be accepted on a case by case basis. No late homeworks will be accepted after the key is provided.

-   Voicing concerns and evaluations

    -   Please feel free to bring up any concerns you have about the course material, how it is being presented, or how you are being evaluated at any time during the semester. I want you to know that your voice will be heard.

    -   Please complete the end of course evaluations. They are a valuable resource for me and help to guide changes from year to year. I read all comments and will take them seriously. Comments about what worked well as well as constructive criticism are appreciated

## Accommodations

-   I encourage students who encounter accessibility challenges to communicate with me regardless of whether they are registered with Equal Opportunity and Access

-   Please communicate with me at your earliest convenience so we can discuss specific actions to address your needs. I will make every effort to accommodate reasonable requests.

-   If you have established accommodations with Equal Opportunity and Access, I will receive an email notifying me of the request.

-   If you need to contact Equal Opportunity and Access to establish service, the address is https://www.vanderbilt.edu/eeo/disability_services/contact_us.php
