<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.1.251">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Chris Slaughter">

<title>BIOS 6312 - Spring 2024 - Logistic Regression</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../notes/Lec05.Precision.html" rel="next">
<link href="../notes/Lec03.SimpleLinearRegression.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/bootstrap/bootstrap-dark.min.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<meta property="og:title" content="BIOS 6312 - Spring 2024 - Logistic Regression">
<meta property="og:description" content="Lecture 04">
<meta property="og:site-name" content="BIOS 6312 - Spring 2024">
</head>

<body class="nav-sidebar docked slimcontent">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
    <div class="container-fluid d-flex justify-content-between">
      <h1 class="quarto-secondary-nav-title">Logistic Regression</h1>
      <button type="button" class="quarto-btn-toggle btn" aria-label="Show secondary navigation">
        <i class="bi bi-chevron-right"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-center sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">BIOS 6312 - Spring 2024</a> 
        <div class="sidebar-tools-main">
  <a href="" class="quarto-color-scheme-toggle sidebar-tool" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
    </div>
      </div>
      <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
      </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="false">Course Introduction</a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="false">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notes/Lec01.Introduction.html" class="sidebar-item-text sidebar-link">Welcome &amp; Syllabus</a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">Course Notes</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notes/Lec02.review.html" class="sidebar-item-text sidebar-link">Review of Key Concepts</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notes/Lec03.SimpleLinearRegression.html" class="sidebar-item-text sidebar-link">Simple Linear Regression</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notes/Lec04.Logistic.html" class="sidebar-item-text sidebar-link active">Logistic Regression</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notes/Lec05.Precision.html" class="sidebar-item-text sidebar-link">Precision of Statistical Intefence</a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="false">Labs</a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="false">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../labs/quarto-intro.html" class="sidebar-item-text sidebar-link">Quarto Introduction</a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="false">Supplemental notes</a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="false">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../supplemental/slr-derivations.html" class="sidebar-item-text sidebar-link">SLR derivations</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../supplemental/model-diagnostics-matrix.html" class="sidebar-item-text sidebar-link">Model diagnostics</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../supplemental/mlr-matrix.html" class="sidebar-item-text sidebar-link">MLR matrix notation</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../supplemental/log-transformations.html" class="sidebar-item-text sidebar-link">Log transformations</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../supplemental/model-selection-criteria.html" class="sidebar-item-text sidebar-link">Model selection criteria</a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
    <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Contents</h2>
   
  <ul>
  <li><a href="#general-regression-setting" id="toc-general-regression-setting" class="nav-link active" data-scroll-target="#general-regression-setting"><span class="toc-section-number">1</span>  General Regression Setting</a>
  <ul>
  <li><a href="#uses-of-general-regression" id="toc-uses-of-general-regression" class="nav-link" data-scroll-target="#uses-of-general-regression"><span class="toc-section-number">1.1</span>  Uses of General Regression</a></li>
  </ul></li>
  <li><a href="#simple-logistic-regression" id="toc-simple-logistic-regression" class="nav-link" data-scroll-target="#simple-logistic-regression"><span class="toc-section-number">2</span>  Simple Logistic Regression</a>
  <ul>
  <li><a href="#uses-of-logistic-regression" id="toc-uses-of-logistic-regression" class="nav-link" data-scroll-target="#uses-of-logistic-regression"><span class="toc-section-number">2.1</span>  Uses of logistic regression</a></li>
  <li><a href="#reasons-to-use-logistic-regression" id="toc-reasons-to-use-logistic-regression" class="nav-link" data-scroll-target="#reasons-to-use-logistic-regression"><span class="toc-section-number">2.2</span>  Reasons to use logistic regression</a></li>
  <li><a href="#the-simple-logistic-regression-model" id="toc-the-simple-logistic-regression-model" class="nav-link" data-scroll-target="#the-simple-logistic-regression-model"><span class="toc-section-number">2.3</span>  The simple logistic regression model</a></li>
  </ul></li>
  <li><a href="#example-survival-on-the-titanic-and-age" id="toc-example-survival-on-the-titanic-and-age" class="nav-link" data-scroll-target="#example-survival-on-the-titanic-and-age"><span class="toc-section-number">3</span>  Example: Survival on the Titanic and Age</a>
  <ul>
  <li><a href="#descriptive-plots" id="toc-descriptive-plots" class="nav-link" data-scroll-target="#descriptive-plots"><span class="toc-section-number">3.1</span>  Descriptive Plots</a></li>
  <li><a href="#regression-model" id="toc-regression-model" class="nav-link" data-scroll-target="#regression-model"><span class="toc-section-number">3.2</span>  Regression Model</a></li>
  <li><a href="#comments-on-interpretation" id="toc-comments-on-interpretation" class="nav-link" data-scroll-target="#comments-on-interpretation"><span class="toc-section-number">3.3</span>  Comments on Interpretation</a>
  <ul class="collapse">
  <li><a href="#bayesian-estimates-and-interpretation" id="toc-bayesian-estimates-and-interpretation" class="nav-link" data-scroll-target="#bayesian-estimates-and-interpretation"><span class="toc-section-number">3.3.1</span>  Bayesian Estimates and Interpretation</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#inference-with-logistic-regression" id="toc-inference-with-logistic-regression" class="nav-link" data-scroll-target="#inference-with-logistic-regression"><span class="toc-section-number">4</span>  Inference with Logistic Regression</a>
  <ul>
  <li><a href="#interpreting-positive-results" id="toc-interpreting-positive-results" class="nav-link" data-scroll-target="#interpreting-positive-results"><span class="toc-section-number">4.1</span>  Interpreting “Positive” Results</a></li>
  <li><a href="#interpreting-negative-results" id="toc-interpreting-negative-results" class="nav-link" data-scroll-target="#interpreting-negative-results"><span class="toc-section-number">4.2</span>  Interpreting “Negative” Results</a></li>
  </ul></li>
  <li><a href="#example-analysis-revisited-effect-modification" id="toc-example-analysis-revisited-effect-modification" class="nav-link" data-scroll-target="#example-analysis-revisited-effect-modification"><span class="toc-section-number">5</span>  Example analysis revisited: Effect Modification</a>
  <ul>
  <li><a href="#stratified-analysis-by-sex" id="toc-stratified-analysis-by-sex" class="nav-link" data-scroll-target="#stratified-analysis-by-sex"><span class="toc-section-number">5.1</span>  Stratified analysis by sex</a>
  <ul class="collapse">
  <li><a href="#odds-ratios-and-confidence-intervals-for-age-effect-by-sex" id="toc-odds-ratios-and-confidence-intervals-for-age-effect-by-sex" class="nav-link" data-scroll-target="#odds-ratios-and-confidence-intervals-for-age-effect-by-sex"><span class="toc-section-number">5.1.1</span>  Odds ratios and confidence intervals for age effect by sex</a></li>
  </ul></li>
  <li><a href="#effect-modification-using-interaction-terms" id="toc-effect-modification-using-interaction-terms" class="nav-link" data-scroll-target="#effect-modification-using-interaction-terms"><span class="toc-section-number">5.2</span>  Effect modification using interaction terms</a></li>
  </ul></li>
  </ul>
<div class="toc-actions"><div><i class="bi bi-github"></i></div><div class="action-links"><p><a href="https://github.com/bios6312/website/edit/main/notes/Lec04.Logistic.qmd" class="toc-action">Edit this page</a></p><p><a href="https://github.com/bios6312/website/issues/new" class="toc-action">Report an issue</a></p></div></div></nav>
</nav>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
    </div>
<!-- main -->
<main class="content page-columns page-full" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title d-none d-lg-block">Logistic Regression</h1><button type="button" class="btn code-tools-button dropdown-toggle" id="quarto-code-tools-menu" data-bs-toggle="dropdown" aria-expanded="false"><i class="bi"></i> Code</button><ul class="dropdown-menu dropdown-menu-end" aria-labelelledby="quarto-code-tools-menu"><li><a id="quarto-show-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Show All Code</a></li><li><a id="quarto-hide-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Hide All Code</a></li><li><hr class="dropdown-divider"></li><li><a id="quarto-view-source" class="dropdown-item" href="javascript:void(0)" role="button">View Source</a></li></ul></div></div>
<p class="subtitle lead">Lecture 04</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Chris Slaughter </p>
          </div>
  </div>
    
    
  </div>
  

</header>

<section id="general-regression-setting" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="general-regression-setting"><span class="header-section-number">1</span> General Regression Setting</h2>
<ul>
<li><p>Types of variables</p>
<ul>
<li><p>Binary data: e.g.&nbsp;sex, death</p></li>
<li><p>Nominal (unordered categorical) data: e.g.&nbsp;race, martial status</p></li>
<li><p>Ordinal (ordered categorical data): e.g.&nbsp;cancer stage, asthma severity</p></li>
<li><p>Quantitative data: e.g.&nbsp;age, blood pressure</p></li>
<li><p>Right censored data: e.g.&nbsp;time to death</p></li>
</ul></li>
<li><p>The measures used to summarize and compare distributions vary according to the type of variable</p>
<ul>
<li><p>Means: Binary, quantitative</p></li>
<li><p>Medians: Ordered, quantitative, censored</p></li>
<li><p>Proportions: Binary, nominal, ordinal</p></li>
<li><p>Odds: Binary, nominal, ordinal</p></li>
<li><p>Hazards: Censored</p></li>
</ul></li>
<li><p>Which regression model you choose to use is based on the parameter being compared across groups</p></li>
</ul>
<div class="center">
<table class="table">
<thead>
<tr class="header">
<th style="text-align: left;">Parameter</th>
<th style="text-align: left;">Approach</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Means</td>
<td style="text-align: left;">Linear regression</td>
</tr>
<tr class="even">
<td style="text-align: left;">Geometric means</td>
<td style="text-align: left;">Linear regression on log scale</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Odds</td>
<td style="text-align: left;">Logistic regression</td>
</tr>
<tr class="even">
<td style="text-align: left;">Rates</td>
<td style="text-align: left;">Poisson regression</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Hazards</td>
<td style="text-align: left;">Proportional Hazards (Cox) regression</td>
</tr>
</tbody>
</table>
</div>
<ul>
<li>General notation for variables and parameters</li>
</ul>
<div class="center">
<table class="table">
<tbody>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(Y_i\)</span></td>
<td style="text-align: left;">Response measured on the <span class="math inline">\(i\)</span>th subject</td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="math inline">\(X_i\)</span></td>
<td style="text-align: left;">Value of the predictor measured on the <span class="math inline">\(i\)</span>th subject</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(\theta_i\)</span></td>
<td style="text-align: left;">Parameter summarizing distribution of <span class="math inline">\(Y_i | X_i\)</span></td>
</tr>
</tbody>
</table>
</div>
<ul>
<li><p>The parameter (<span class="math inline">\(\theta_i\)</span>) might be the mean, geometric mean, odds, rate, instantaneous risk of an event (hazard), etc.</p></li>
<li><p>In linear regression on means, <span class="math inline">\(\theta_i = E[Y_i | X_i]\)</span></p></li>
<li><p>Choice of correct <span class="math inline">\(\theta_i\)</span> should be based on scientific understanding of problem</p></li>
<li><p>General notation for simple regression model</p></li>
</ul>
<p><span class="math display">\[g(\theta_i) = \beta_0 + \beta_1 \times X_i\]</span></p>
<div class="center">
<p>General notation for regression model with one predictor</p>
<table class="table">
<tbody>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(g( )\)</span></td>
<td style="text-align: left;">Link function used for modeling</td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="math inline">\(\beta_0\)</span></td>
<td style="text-align: left;">Intercept</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(\beta_1\)</span></td>
<td style="text-align: left;">Slope for predictor <span class="math inline">\(X\)</span></td>
</tr>
</tbody>
</table>
</div>
<ul>
<li><p>The link function is often either the identity function (for modeling means) or log (for modeling geometric means, odds, hazards)</p>
<ul>
<li>Identity function: <span class="math inline">\(f(x) = x\)</span></li>
</ul></li>
</ul>
<section id="uses-of-general-regression" class="level3" data-number="1.1">
<h3 data-number="1.1" class="anchored" data-anchor-id="uses-of-general-regression"><span class="header-section-number">1.1</span> Uses of General Regression</h3>
<ul>
<li><p>Borrowing information</p>
<ul>
<li><p>Use other groups to make estimates in groups with sparse data</p></li>
<li><p>Intuitively, 67 and 69 year olds would provide some relevant information about 68 year olds</p></li>
<li><p>Assuming a straight line relationship tells us about other, even more distant, individuals</p></li>
<li><p>If we do not want to assume a straight line, we may only want to borrow information from nearby groups</p></li>
</ul></li>
<li><p>Defining “Contrasts”</p>
<ul>
<li><p>Define a comparison across groups to use when answering scientific questions</p></li>
<li><p>If the straight line relationship holds, the slope is the difference in parameter between groups differing by 1 unit in <span class="math inline">\(X\)</span></p></li>
<li><p>If a non-linear relationship in parameter, the slope is still the average difference in parameter between groups differing by 1 unit in <span class="math inline">\(X\)</span></p></li>
<li><p>Slope is a (first order or linear) test for trend in the parameter</p></li>
<li><p>Statistical jargon: “a contrast” across groups</p></li>
</ul></li>
<li><p>The major difference between different regression models is the interpretation of the parameters</p>
<ul>
<li><p>How do I want to summarize the outcome?</p></li>
<li><p>Mean, geometric mean, odds, hazard</p></li>
</ul></li>
<li><p>How do I want to compare groups?</p>
<ul>
<li>Difference, ratio</li>
</ul></li>
<li><p>Answering these two simple questions provides a starting road-map as to which regression model to choose</p></li>
<li><p>Issues related to the inclusion of covariates remains the same</p>
<ul>
<li><p>Address the scientific question: Predictor of interest, effect modification</p></li>
<li><p>Address confounding</p></li>
<li><p>Increase precision</p></li>
</ul></li>
</ul>
</section>
</section>
<section id="simple-logistic-regression" class="level2 page-columns page-full" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="simple-logistic-regression"><span class="header-section-number">2</span> Simple Logistic Regression</h2>
<section id="uses-of-logistic-regression" class="level3" data-number="2.1">
<h3 data-number="2.1" class="anchored" data-anchor-id="uses-of-logistic-regression"><span class="header-section-number">2.1</span> Uses of logistic regression</h3>
<ul>
<li><p>Use logistic regression when you want to make inference about the odds</p>
<ul>
<li><p>Allows for continuous (or multiple) grouping variables</p></li>
<li><p>Is OK with binary grouping variables too</p></li>
<li><p>Compares odds of responses across groups using ratios</p>
<ul>
<li>“Odds ratio”</li>
</ul></li>
</ul></li>
<li><p>Binary response variable</p></li>
<li><p>When using regression with binary response variables, we typically model the (log) odds using logistic regression</p>
<ul>
<li><p>Conceptually there should be no problem modeling the proportion (which is the mean of the distribution)</p></li>
<li><p>However, there are several technical reasons why we do not use linear regression very often with binary responses</p></li>
<li><p>Why not use linear regression for binary responses?</p></li>
</ul></li>
<li><p>Many misconceptions about the advantages and disadvantages of analyzing the odds</p>
<ul>
<li><p>Reasons I consider valid: Scientific basis</p>
<ul>
<li><p>Uses of odds ratios in case control studies</p></li>
<li><p>Plausibility of linear trends and no effect modifiers</p></li>
</ul></li>
<li><p>Reasons I consider valid: Statistical basis</p>
<ul>
<li>There is a mean variance relationship (if not using robust SE) that can be incorporate in the logistic regression model</li>
</ul></li>
</ul></li>
</ul>
</section>
<section id="reasons-to-use-logistic-regression" class="level3 page-columns page-full" data-number="2.2">
<h3 data-number="2.2" class="anchored" data-anchor-id="reasons-to-use-logistic-regression"><span class="header-section-number">2.2</span> Reasons to use logistic regression</h3>
<ul>
<li><p>First (scientific) reason: Case-Control Studies</p>
<ul>
<li><p>Studying a rare disease, so we do study in reverse</p>
<ul>
<li><p>e.g.&nbsp;find subjects with cancer (and suitable controls) and then ascertain exposure of interest</p></li>
<li><p>Estimate distribution of the “effect” across groups defined by “cause”</p></li>
<li><p>Proportion (or odds) of smokers among people with or without lung cancer</p></li>
</ul></li>
</ul>
<table class="table">
<caption>Case-Control or Cohort 2x2 Table. In the Case-Control design, the total number of subjects with Cancer <span class="math inline">\((a+c)\)</span> and without cancer <span class="math inline">\((b+d)\)</span> are fixed by design.</caption>
<tbody>
<tr class="odd">
<td></td>
<td>Lung Cancer +</td>
<td>Lung Cancer -</td>
</tr>
<tr class="even">
<td>Smoker</td>
<td>a</td>
<td>b</td>
</tr>
<tr class="odd">
<td>Non-Smoker</td>
<td>c</td>
<td>d</td>
</tr>
</tbody>
</table>
<ul>
<li><p>In contrast, a cohort study samples by exposure (smoking) and then estimates the distribution of the effect in exposure groups</p></li>
<li><p>In a case-control study, we cannot estimate prevalence (without knowing selection probabilities)</p>
<ul>
<li>e.g.&nbsp;if doing a 1:1 case-control study, <span class="math inline">\((a+c) = b+d\)</span> so it would look like <span class="math inline">\(50\%\)</span> of the subjects have cancer</li>
</ul></li>
<li><p>Odds ratios are estimable in either case-control or cohort sampling scheme</p>
<ul>
<li><p>Cohort study: Odds of cancer among smoker compared to odds of cancer among nonsmokers</p></li>
<li><p>Case-control study: Odds of smoking among cancer compared to odds of smoking among non-cancer</p></li>
</ul></li>
<li><p>Mathematically, these two odds ratios are the same</p>
<ul>
<li></li>
</ul></li>
<li><p>Odds ratios are easy to interpret when investigating rare events</p>
<ul>
<li><p>Odds = prob / (1 - prob)</p></li>
<li><p>For rare events, (1 - prob) is approximately 1</p>
<ul>
<li><p>Odds is approximately the probability</p></li>
<li><p>Odds ratios are approximately risk ratios</p></li>
</ul></li>
<li><p>Case-control studies usually used when events are rare</p></li>
</ul></li>
</ul></li>
<li><p>Second (scientific) reason: Linearity</p>
<ul>
<li><p>Proportions are bounded by 0 and 1</p></li>
<li><p>It is thus unlikely that a straight line relationship would exists between a proportion and a predictor</p>
<ul>
<li><p>Unless the predictor itself is bounded</p></li>
<li><p>Otherwise, there eventually must be a threshold above which the probability does not increase (or only increases a little)</p></li>
</ul></li>
</ul></li>
</ul>
<div class="cell page-columns page-full">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>expit <span class="ot">&lt;-</span> <span class="cf">function</span>(x) {<span class="fu">exp</span>(x)<span class="sc">/</span>(<span class="dv">1</span><span class="sc">+</span><span class="fu">exp</span>(x))}</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="cf">function</span>(x) <span class="fu">expit</span>(x), <span class="sc">-</span><span class="dv">4</span>,<span class="dv">4</span>, <span class="at">ylab=</span><span class="st">"Probabilty"</span>, <span class="at">xlab=</span><span class="st">"Predictor"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display page-columns page-full">
<div class="quarto-figure quarto-figure-center page-columns page-full">
<figure class="figure page-columns page-full">
<p><img src="Lec04.Logistic_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid figure-img" width="672"></p>
<p></p><figcaption class="figure-caption margin-caption">Logistic function will bound probabilities between 0 and 1</figcaption><p></p>
</figure>
</div>
</div>
</div>
<ul>
<li><p>Third (scientific) reason: Effect modification</p>
<ul>
<li><p>The restriction on ranges for probabilities makes it likely that effect modification <em>must</em> be present with proportions</p></li>
<li><p>Example: Is the association between 2-year relapse rates and having a positive scan modified by gender?</p>
<ul>
<li><p>Women relapse 40% of the time when the scan is negative, and 95% of the time when the scan is positive (an increase of 55%)</p>
<ul>
<li><p>If men relapse 75% of the time when the scan is negative, then a positive scan can increase the relapse rate to at most 100%, which is only a 25% increase</p>
<table class="table">
<tbody>
<tr class="odd">
<td><strong>Proportions</strong></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td></td>
<td>Women</td>
<td>Men</td>
</tr>
<tr class="odd">
<td>Negative Scan</td>
<td>40%</td>
<td>75%</td>
</tr>
<tr class="even">
<td>Positive Scan</td>
<td>95%</td>
<td>(up to 100%)</td>
</tr>
<tr class="odd">
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td>Difference</td>
<td>55%</td>
<td>Up to 25%</td>
</tr>
<tr class="odd">
<td>Ratio</td>
<td>1.64</td>
<td><span class="math inline">\(\leq 1.33\)</span></td>
</tr>
</tbody>
</table></li>
<li><p>With the odds, the association can hold without effect modification</p>
<table class="table">
<tbody>
<tr class="odd">
<td><strong>Odds</strong></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td></td>
<td>Women</td>
<td>Men</td>
</tr>
<tr class="odd">
<td>Negative Scan</td>
<td>0.67</td>
<td>3</td>
</tr>
<tr class="even">
<td>Positive Scan</td>
<td>19</td>
<td>(up to <span class="math inline">\(\infty\)</span>)</td>
</tr>
<tr class="odd">
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td>Ratio</td>
<td>28.5</td>
<td><span class="math inline">\(&lt; \infty\)</span></td>
</tr>
</tbody>
</table></li>
</ul></li>
</ul></li>
</ul></li>
<li><p>If the o dds of positive scan in men was 85.5, then the odds ratio would be exactly 28.5 (no effect modification)</p></li>
<li><p>Fourth (statistics) reason:</p>
<ul>
<li><p>Classical linear regression requires equal variances across each predictor group</p></li>
<li><p>But, with binary data, the variance within a group depends on the mean</p></li>
<li><p>For binary <span class="math inline">\(Y\)</span>, <span class="math inline">\(E(Y) = p\)</span> and <span class="math inline">\(Var(Y) = p(1-p)\)</span></p></li>
<li><p>With robust standard errors, the mean-variance relationship is not a major problem. However, a logistic model that correctly models the mean-variance relationship will be more efficient.</p></li>
</ul></li>
</ul>
</section>
<section id="the-simple-logistic-regression-model" class="level3" data-number="2.3">
<h3 data-number="2.3" class="anchored" data-anchor-id="the-simple-logistic-regression-model"><span class="header-section-number">2.3</span> The simple logistic regression model</h3>
<ul>
<li><p>Modeling the odds of binary response variable <span class="math inline">\(Y\)</span> on predictor <span class="math inline">\(X\)</span></p>
<ul>
<li><p>Distribution: <span class="math inline">\(\textrm{Pr}(Y_i = 1) = p_i\)</span></p></li>
<li><p>Model: <span class="math inline">\(\textrm{logit}(p_i) = \textrm{log}\left(\frac{p_i}{1-p_i}\right) = \beta_0 + \beta_1 \times X_i\)</span></p></li>
<li><p>When <span class="math inline">\(X_i = 0\)</span>: log odds = <span class="math inline">\(\beta_0\)</span></p></li>
<li><p>When <span class="math inline">\(X_i = x\)</span>: log odds = <span class="math inline">\(\beta_0 + \beta_1 \times x\)</span></p></li>
<li><p>When <span class="math inline">\(X_i = x+1\)</span>: log odds = <span class="math inline">\(\beta_0 + \beta_1 \times x + \beta_1\)</span></p></li>
</ul></li>
<li><p>To interpret as odds, exponentiate the regression parameters</p>
<ul>
<li>Distribution: <span class="math inline">\(\textrm{Pr}(Y_i = 1) = p_i\)</span></li>
<li>Model: <span class="math inline">\(\frac{p_i}{1-p_i} = \exp(\beta_0 + \beta_1 \times X_i) = e^{\beta_0} \times e^{\beta_1 \times X_i}\)</span></li>
<li>When <span class="math inline">\(X_i = 0\)</span>: odds = <span class="math inline">\(e^{\beta_0}\)</span></li>
<li>When <span class="math inline">\(X_i = x\)</span>: odds = <span class="math inline">\(e^{\beta_0} \times e^{\beta_1 \times x}\)</span></li>
<li>When <span class="math inline">\(X_i = x+1\)</span>: odds = <span class="math inline">\(e^{\beta_0} \times e^{\beta_1 \times x} \times e^{\beta_1}\)</span></li>
</ul></li>
<li><p>To interpret as proportions (remember proportion = odds / (1 + odds))</p>
<ul>
<li>Distribution: <span class="math inline">\(\textrm{Pr}(Y_i = 1) = p_i\)</span></li>
<li>Model: <span class="math inline">\(p_i = \frac{e^{\beta_0} e^{\beta_1 \times X_i}}{1 + e^{\beta_0} e^{\beta_1 \times X_i}}\)</span></li>
<li>When <span class="math inline">\(X_i = 0\)</span>: <span class="math inline">\(p_i = \frac{e^{\beta_0}}{1 + e^{\beta_0}}\)</span><br>
</li>
<li>When <span class="math inline">\(X_i = x\)</span>: <span class="math inline">\(p_i = \frac{e^{\beta_0} e^{\beta_1 \times x}}{1 + e^{\beta_0} e^{\beta_1 \times x}}\)</span></li>
<li>When <span class="math inline">\(X_i = x+1\)</span>: <span class="math inline">\(p_i = \frac{e^{\beta_0} e^{\beta_1 \times x} e^{\beta_1}}{1 + e^{\beta_0} e^{\beta_1 \times x}e^{\beta_1}}\)</span></li>
</ul></li>
<li><p>Most common interpretations found by exponentiating the coefficients</p>
<ul>
<li><p>Odds when predictor is 0 found by exponentiating the intercept: <span class="math inline">\(\exp(\beta_0)\)</span></p></li>
<li><p>Odds ratio between groups differing in the values of the predictor by 1 unit found by exponentiating the slope: <span class="math inline">\(\exp(\beta_1)\)</span></p></li>
</ul></li>
<li><p>Stata commands</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode stata code-with-copy"><code class="sourceCode stata"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="kw">logit</span> respvar predvar, [<span class="kw">robust</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<ul>
<li>Provides regression parameter estimates an inference on the log odds scale (both coefficients with CIs, SEs, p-values)</li>
</ul>
<div class="sourceCode" id="cb3"><pre class="sourceCode stata code-with-copy"><code class="sourceCode stata"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="kw">logistic</span> respvar predvar, [<span class="kw">robust</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<ul>
<li>Provides regression parameter estimates and inference on the odds ratio scale (only slope with CIs, SEs, p-values)</li>
</ul></li>
<li><p>R Commands</p>
<ul>
<li><p>With rms package, <code>lrm(respvar ~ predvar, ...)</code></p></li>
<li><p>In general, <code>glm(respvar ~ predvar, family=“binomial”)</code></p></li>
</ul></li>
</ul>
</section>
</section>
<section id="example-survival-on-the-titanic-and-age" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="example-survival-on-the-titanic-and-age"><span class="header-section-number">3</span> Example: Survival on the Titanic and Age</h2>
<ul>
<li><p>Dataset at <a href="https://biostat.app.vumc.org/DataSets" class="uri">https://biostat.app.vumc.org/DataSets</a></p></li>
<li><p>Describes the survival status of individual passengers on the Titanic</p></li>
<li><p>Data on age available for many, but not all, subjects (data continually being updated)</p></li>
<li><p>Response variables is Survival</p>
<ul>
<li>Binary variable: 1=Survived, 0=Died</li>
</ul></li>
<li><p>Predictor variable is Age</p>
<ul>
<li>Continuous grouping variable</li>
</ul></li>
<li><p>Possibly different age effects by sex (effect modification by sex)</p></li>
</ul>
<section id="descriptive-plots" class="level3" data-number="3.1">
<h3 data-number="3.1" class="anchored" data-anchor-id="descriptive-plots"><span class="header-section-number">3.1</span> Descriptive Plots</h3>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># | fig-cap: Missing data patterns in the Tianic dataset</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(rms)</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>titanic <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="at">file=</span><span class="st">"data/titanic3.csv"</span>)</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">naclus</span>(titanic)) <span class="co"># study patterns of missing values</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="Lec04.Logistic_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># | fig-cap: Scatterplot of age versus survival in the Titanic data with lowess smooth.  This simple plot is not very useful because survival is either 0 or 1, making it hard to visualize any trends.</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(titanic, <span class="fu">aes</span>(<span class="at">x=</span>age, <span class="at">y=</span>survived)) <span class="sc">+</span> <span class="fu">geom_jitter</span>(<span class="at">width=</span><span class="dv">0</span>, <span class="at">height=</span>.<span class="dv">02</span>, <span class="at">alpha=</span>.<span class="dv">5</span>) <span class="sc">+</span> <span class="fu">geom_smooth</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="Lec04.Logistic_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># | fig-cap: Age versus survival by sex in the Titanic data by age using a super smoother.  The trends are clearer with this smoothing approach.</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="fu">with</span>(titanic, </span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>     <span class="fu">plsmo</span>(age, survived, <span class="at">group=</span>sex, <span class="at">datadensity=</span>T, <span class="at">ylab=</span><span class="st">"Survived (1=Yes, 0=No)"</span>, <span class="at">xlab=</span><span class="st">"Age (years)"</span>)</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="Lec04.Logistic_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">

</div>
<ul>
<li><p>Comments on the plots</p>
<ul>
<li><p>Age is missing for many subjects, which we will not worry about in the following analysis</p></li>
<li><p>The simple scatterplot, even with superimposes lowess smooth, is worthless. I have jittered the point and altered their opacity to help visualize overlapping point.</p></li>
<li><p>More advanced plotting available in R (in this case, the plsmo() function) can help to visualize the data</p></li>
</ul></li>
</ul>
</section>
<section id="regression-model" class="level3" data-number="3.2">
<h3 data-number="3.2" class="anchored" data-anchor-id="regression-model"><span class="header-section-number">3.2</span> Regression Model</h3>
<ul>
<li><p>Regression model for survival on age (ignoring possible effect modification for now)</p></li>
<li><p>Answer question by assessing linear trends in log odds of survival by age</p></li>
<li><p>Estimate the best fitting line to log odds of survival within age groups</p></li>
</ul>
<p><span class="math display">\[\textrm{logodds}(\textrm{Survival} | \textrm{Age}) = \beta_0 + \beta_1 \times \textrm{Age}\]</span></p>
<ul>
<li><p>An association will exist if the slope <span class="math inline">\(\beta_1\)</span> is nonzero</p></li>
<li><p>In that case, the odds (and probability) of survival will be different across different age groups</p></li>
</ul>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>m.titanic <span class="ot">&lt;-</span> <span class="fu">glm</span>(survived <span class="sc">~</span> age, <span class="at">data=</span>titanic, <span class="at">family =</span> <span class="st">"binomial"</span>)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m.titanic)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = survived ~ age, family = "binomial", data = titanic)

Coefficients:
             Estimate Std. Error z value Pr(&gt;|z|)  
(Intercept) -0.136534   0.144715  -0.943   0.3454  
age         -0.007899   0.004407  -1.792   0.0731 .
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 1414.6  on 1045  degrees of freedom
Residual deviance: 1411.4  on 1044  degrees of freedom
  (263 observations deleted due to missingness)
AIC: 1415.4

Number of Fisher Scoring iterations: 4</code></pre>
</div>
</div>
<p><span class="math inline">\(\textrm{logodds}(\textrm{Survival} | \textrm{Age}) = -0.1365 - 0.007899 \times \textrm{Age}\)</span></p>
<ul>
<li><p>General interpretation</p>
<ul>
<li><p>Intercept is labeled “(Intercept)”</p></li>
<li><p>Slope for age is labeled “age”</p></li>
</ul></li>
<li><p>Interpretation of intercept</p>
<p>*Estimated log odds for newborns (age=0) is <span class="math inline">\(-0.136534\)</span></p>
<ul>
<li><p>Odds of survival for newborns is <span class="math inline">\(e^{-0.136534} = 0.8724\)</span></p></li>
<li><p>Probability of survival</p>
<ul>
<li><p>Prob = odds / (1 + odds)</p></li>
<li><p><span class="math inline">\(0.8724 / (1 + .8724) = 0.4659\)</span></p></li>
</ul></li>
</ul></li>
</ul>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(m.titanic, <span class="at">newdata=</span><span class="fu">data.frame</span>(<span class="at">age=</span><span class="dv">0</span>), <span class="at">type=</span><span class="st">'response'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>        1 
0.4659194 </code></pre>
</div>
</div>
<ul>
<li><p>Interpretation of slope</p>
<ul>
<li><p>Estimate difference in the log odds of survival for two groups differing by one year in age is <span class="math inline">\(-0.0078985\)</span></p></li>
<li><p>This estimate averages over males and females</p></li>
<li><p>Older groups tend to have lower log odds</p></li>
<li><p>Odds Ratio: <span class="math inline">\(e^{-0.0078985} = 0.9921\)</span></p></li>
<li><p>For five year difference in age: <span class="math inline">\(e^{-0.0078985 \times 5} = 0.9612\)</span></p></li>
<li><p>In Stata use “lincom age, or” or “lincom 5*age, or”</p></li>
</ul></li>
</ul>
<p>Note that if the straight line relationship does not hold true, we interpret the slope as an average difference in the log odds of survival per one year difference in age</p>
<p>There are several ways to get the odds ratio and confidence interval in R</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># The coefficient and confidence interval (on the log-odds scale)</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(m.titanic)[<span class="st">"age"</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>         age 
-0.007898504 </code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confint.default</span>(m.titanic, <span class="st">"age"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>          2.5 %       97.5 %
age -0.01653509 0.0007380868</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Odds ratio for age and confidence interval for age (1 year increase)</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(<span class="fu">coef</span>(m.titanic)[<span class="st">"age"</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>      age 
0.9921326 </code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(<span class="fu">confint.default</span>(m.titanic, <span class="st">"age"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>        2.5 %   97.5 %
age 0.9836009 1.000738</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Odds ratio for age and confidence interval for age (5 year increase)</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(<span class="dv">5</span><span class="sc">*</span><span class="fu">coef</span>(m.titanic)[<span class="st">"age"</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>      age 
0.9612771 </code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(<span class="dv">5</span><span class="sc">*</span><span class="fu">confint.default</span>(m.titanic, <span class="st">"age"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>        2.5 %   97.5 %
age 0.9206499 1.003697</code></pre>
</div>
</div>
<ul>
<li><p>Using finalfit to create a nicer output table of the coefficients and confidence intervals</p>
<ul>
<li>For finalfit to use a logistic regression model by default, survived must be defined as a factor variable with two levels</li>
</ul></li>
</ul>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>mykable <span class="ot">=</span> <span class="cf">function</span>(x){</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>  knitr<span class="sc">::</span><span class="fu">kable</span>(x, <span class="at">row.names =</span> <span class="cn">FALSE</span>, <span class="at">align =</span> <span class="fu">c</span>(<span class="st">"l"</span>, <span class="st">"l"</span>, <span class="st">"r"</span>, <span class="st">"r"</span>, <span class="st">"r"</span>, <span class="st">"r"</span>, <span class="st">"r"</span>, <span class="st">"r"</span>, <span class="st">"r"</span>),</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>               <span class="at">booktabs=</span><span class="cn">TRUE</span>)</span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(finalfit)</span>
<span id="cb23-8"><a href="#cb23-8" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb23-9"><a href="#cb23-9" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(rms)</span>
<span id="cb23-10"><a href="#cb23-10" aria-hidden="true" tabindex="-1"></a>explanatory <span class="ot">=</span> <span class="fu">c</span>(<span class="st">"age"</span>)</span>
<span id="cb23-11"><a href="#cb23-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-12"><a href="#cb23-12" aria-hidden="true" tabindex="-1"></a>titanic<span class="sc">$</span>survived.factor <span class="ot">&lt;-</span> <span class="fu">factor</span>(titanic<span class="sc">$</span>survived, <span class="at">levels=</span><span class="dv">0</span><span class="sc">:</span><span class="dv">1</span>, <span class="at">labels=</span><span class="fu">c</span>(<span class="st">"Died"</span>,<span class="st">"Survived"</span>))</span>
<span id="cb23-13"><a href="#cb23-13" aria-hidden="true" tabindex="-1"></a>dependent <span class="ot">=</span> <span class="st">'survived.factor'</span></span>
<span id="cb23-14"><a href="#cb23-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-15"><a href="#cb23-15" aria-hidden="true" tabindex="-1"></a><span class="fu">label</span>(titanic<span class="sc">$</span>age) <span class="ot">&lt;-</span> <span class="st">"Age (years)"</span></span>
<span id="cb23-16"><a href="#cb23-16" aria-hidden="true" tabindex="-1"></a>titanic <span class="sc">%&gt;%</span> </span>
<span id="cb23-17"><a href="#cb23-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">finalfit</span>(dependent, explanatory) <span class="sc">%&gt;%</span> <span class="fu">mykable</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<table class="table table-sm table-striped">
<colgroup>
<col style="width: 23%">
<col style="width: 8%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 23%">
<col style="width: 23%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Dependent: survived.factor</th>
<th style="text-align: left;"></th>
<th style="text-align: right;">Died</th>
<th style="text-align: right;">Survived</th>
<th style="text-align: right;">OR (univariable)</th>
<th style="text-align: right;">OR (multivariable)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Age (years)</td>
<td style="text-align: left;">Mean (SD)</td>
<td style="text-align: right;">30.5 (13.9)</td>
<td style="text-align: right;">28.9 (15.1)</td>
<td style="text-align: right;">0.99 (0.98-1.00, p=0.073)</td>
<td style="text-align: right;">0.99 (0.98-1.00, p=0.073)</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
<section id="comments-on-interpretation" class="level3" data-number="3.3">
<h3 data-number="3.3" class="anchored" data-anchor-id="comments-on-interpretation"><span class="header-section-number">3.3</span> Comments on Interpretation</h3>
<ul>
<li><p>The slope for age is expressed as a difference in group means, not the difference due to aging. We did not do a longitudinal study in which repeated measurements were taken on the same subject.</p></li>
<li><p>If the group log odds are truly linear, then the slope has an exact interpretation as the change in survival due to a one year change in (any) age</p></li>
<li><p>Otherwise, the slope estimates the first order trend of the sample data and we should not treat the estimates of group odds or probabilities as accurate</p></li>
<li><p>It is difficult to see in the above example, but the CIs around the odds ratios are not symmetric</p>
<ul>
<li>(Symmetric) CIs are calculated on the log odds scale, and then transformed to the odds scale by expoenentiating the lower and upper limits of the CI</li>
</ul></li>
<li><p>“From logistic regression analysis, we estimate that for each 5 year difference in age, the odds of survival on the Titanic decreased by 3.9%, though this estimate is not statistically significant (<span class="math inline">\(p = 0.07\)</span>). A 95% CI suggests that this observation is not unusual if a group that is five years older might have an odds of survival that was anywhere between 7.9% lower and 0.4% higher than the younger group.”</p></li>
<li><p>The confidence interval and statistical test given in the output is called a Wald test. Other tests (Score, Likelihood Ratio) are also possible.</p>
<ul>
<li><p>All tests are asymptotically equivalent</p></li>
<li><p>The Wald test is easiest to obtain, but generally performs the poorest in small sample sizes</p></li>
<li><p>The Likelihood Ratio test performs the best in small samples. We will discuss it later, including how to obtain the test using post-estimation commands.</p></li>
<li><p>The Score test is not bad in small samples, but is often hard to obtain from software. It is exactly equal to the Chi-squared test for binary outcomes and categorical predictors.</p></li>
</ul></li>
</ul>
<section id="bayesian-estimates-and-interpretation" class="level4" data-number="3.3.1">
<h4 data-number="3.3.1" class="anchored" data-anchor-id="bayesian-estimates-and-interpretation"><span class="header-section-number">3.3.1</span> Bayesian Estimates and Interpretation</h4>
<ul>
<li><p>Bayesian approach to the logistic model requires specifying</p>
<ul>
<li><p>The model</p></li>
<li><p>e.g.&nbsp;a model for the log odds of survival that is linear in the parameters with an intercept and slope for age</p></li>
<li><p>Prior distributions on parameters</p>
<ul>
<li><p>For the simple logistic regression model, we have parameters <span class="math inline">\(\beta_0\)</span>, and <span class="math inline">\(\beta_1\)</span>.</p></li>
<li><p>For now, we will use default prior distributions that are are intended to be <em>weakly informative</em> in that they provide moderate regularization and help stabilize computation. See the <a href="https://mc-stan.org/rstanarm/reference/priors.html">STAN documentation</a> for more details</p></li>
<li><p>Appropriate priors can be based on scientific considerations</p></li>
<li><p>Sensitivity analyses can evaluate the the robustness of finding to different prior assumptions</p></li>
</ul></li>
</ul></li>
<li><p>The likelihood</p>
<ul>
<li>For a binomial GLM the likelihood for one observation <span class="math inline">\(y\)</span> can be written as a conditionally binomial probability mass function</li>
</ul></li>
</ul>
<p><span class="math display">\[\binom{n}{y} \pi^{y} (1 - \pi)^{n - y},\]</span></p>
<ul>
<li><p><span class="math inline">\(n\)</span> is the known number of trials, <span class="math inline">\(\pi = g^{-1}(\eta)\)</span> is the probability of success and <span class="math inline">\(\eta = \alpha + \mathbf{x}^\top \boldsymbol{\beta}\)</span> is a linear predictor</p></li>
<li><p>For a sample of size <span class="math inline">\(N\)</span>, the likelihood of the entire sample is the product of <span class="math inline">\(N\)</span> individual likelihood contributions.</p></li>
<li><p>Because <span class="math inline">\(\pi\)</span> is a probability, for a binomial model the <em>link</em> function <span class="math inline">\(g\)</span> maps between the unit interval (the support of <span class="math inline">\(\pi\)</span>) and the set of all real numbers <span class="math inline">\(\mathbb{R}\)</span>. When applied to a linear predictor <span class="math inline">\(\eta\)</span> with values in <span class="math inline">\(\mathbb{R}\)</span>, the inverse link function <span class="math inline">\(g^{-1}(\eta)\)</span> therefore returns a valid probability between 0 and 1.</p></li>
<li><p>The two most common link functions used for binomial GLMs are the</p>
<ul>
<li><a href="https://en.wikipedia.org/wiki/Logit">logit</a> and</li>
<li><a href="https://en.wikipedia.org/wiki/Probit">probit</a></li>
</ul></li>
<li><p>With the logit (or log-odds) link function <span class="math inline">\(g(x) = \ln{\left(\frac{x}{1-x}\right)}\)</span>, the likelihood for a single observation becomes</p></li>
</ul>
<p><span class="math display">\[\binom{n}{y}\left(\text{logit}^{-1}(\eta)\right)^y
\left(1 - \text{logit}^{-1}(\eta)\right)^{n-y} =
\binom{n}{y} \left(\frac{e^{\eta}}{1 + e^{\eta}}\right)^{y}
\left(\frac{1}{1 + e^{\eta}}\right)^{n - y}\]</span></p>
<ul>
<li>With the probit link function <span class="math inline">\(g(x) = \Phi^{-1}(x)\)</span> yields the likelihood</li>
</ul>
<p><span class="math display">\[\binom{n}{y} \left(\Phi(\eta)\right)^{y}
\left(1 - \Phi(\eta)\right)^{n - y},\]</span></p>
<p>where <span class="math inline">\(\Phi\)</span> is the CDF of the standard normal distribution.</p>
<ul>
<li>Output from Bayesian logistic regression using logit link function</li>
</ul>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(rstanarm)</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(bayesplot)</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>fit2 <span class="ot">&lt;-</span> <span class="fu">stan_glm</span>(survived <span class="sc">~</span> age,</span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>                 <span class="at">data=</span>titanic, <span class="at">family=</span><span class="fu">binomial</span>(),</span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a>                 <span class="at">seed=</span><span class="dv">1234</span>,</span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a>                 <span class="at">refresh=</span><span class="dv">0</span>)</span>
<span id="cb24-8"><a href="#cb24-8" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit2, <span class="at">digits=</span><span class="dv">4</span>, <span class="at">prob=</span><span class="fu">c</span>(.<span class="dv">025</span>, .<span class="dv">5</span>, .<span class="dv">975</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Model Info:
 function:     stan_glm
 family:       binomial [logit]
 formula:      survived ~ age
 algorithm:    sampling
 sample:       4000 (posterior sample size)
 priors:       see help('prior_summary')
 observations: 1046
 predictors:   2

Estimates:
              mean    sd      2.5%    50%     97.5%
(Intercept) -0.1343  0.1459 -0.4135 -0.1336  0.1560
age         -0.0079  0.0044 -0.0169 -0.0078  0.0004

Fit Diagnostics:
           mean   sd     2.5%   50%    97.5%
mean_PPD 0.4089 0.0217 0.3652 0.4092 0.4512 

The mean_ppd is the sample average posterior predictive distribution of the outcome variable (for details see help('summary.stanreg')).

MCMC diagnostics
              mcse   Rhat   n_eff
(Intercept)   0.0029 0.9994 2533 
age           0.0001 0.9996 2570 
mean_PPD      0.0004 1.0004 3073 
log-posterior 0.0284 1.0047 1340 

For each parameter, mcse is Monte Carlo standard error, n_eff is a crude measure of effective sample size, and Rhat is the potential scale reduction factor on split chains (at convergence Rhat=1).</code></pre>
</div>
</div>
<ul>
<li>And a summary of the prior distributions used</li>
</ul>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">prior_summary</span>(fit2, <span class="at">digits =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Priors for model 'fit2' 
------
Intercept (after predictors centered)
 ~ normal(location = 0, scale = 2.5)

Coefficients
  Specified prior:
    ~ normal(location = 0, scale = 2.5)
  Adjusted prior:
    ~ normal(location = 0, scale = 0.17)
------
See help('prior_summary.stanreg') for more details</code></pre>
</div>
</div>
<ul>
<li><p>Interpretation</p>
<ul>
<li><p>Slope for age is of primary scientific importance</p></li>
<li><p><em>A priori</em> we assume that no association between age and cholesterol. Specifically, we assumed a Normal prior with location (mean) of 0 and scale (standard devation) of 0.17 for <span class="math inline">\(\beta_1\)</span>.</p></li>
<li><p>Conditional on the data, we estimate that for every 1 year increase in age, the log odds of decreases by -0.0079 (95% credible interval -0.0169 to 0.0004).</p></li>
<li><p>To obtain the posterior odds ratio and 95% credible intervals, some additional commands are needed</p></li>
</ul></li>
</ul>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 1 year change in age</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(<span class="fu">coef</span>(fit2)[<span class="st">"age"</span>]) <span class="co"># Posterior Odds Ratio</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>      age 
0.9922461 </code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(<span class="fu">posterior_interval</span>(fit2, <span class="at">prob =</span> <span class="fl">0.95</span>)) <span class="co"># 95% credible interval</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>                 2.5%    97.5%
(Intercept) 0.6613115 1.168821
age         0.9832330 1.000353</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 5 year change in age</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(<span class="dv">5</span><span class="sc">*</span><span class="fu">coef</span>(fit2)[<span class="st">"age"</span>]) <span class="co"># Posterior Odds Ratio</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>      age 
0.9618272 </code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(<span class="dv">5</span><span class="sc">*</span><span class="fu">posterior_interval</span>(fit2, <span class="at">prob =</span> <span class="fl">0.95</span>))[<span class="dv">2</span>,] <span class="co"># 95% credible interval</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>     2.5%     97.5% 
0.9189294 1.0017684 </code></pre>
</div>
</div>
</section>
</section>
</section>
<section id="inference-with-logistic-regression" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="inference-with-logistic-regression"><span class="header-section-number">4</span> Inference with Logistic Regression</h2>
<ul>
<li><p>The ideas of Signal and Noise found in simple linear regression do not translate well to logistic regression</p></li>
<li><p>We do not tend to quantify an error distribution with logistic regression</p></li>
<li><p>Valid statistical inference (CIs, p-values) about <em>associations</em> requires three general assumptions</p></li>
<li><p>Assumption 1: Approximately Normal distributions for the parameter estimates</p>
<ul>
<li><p>Large N</p></li>
<li><p>Need for either robust standard errors or classical logistic regression</p></li>
<li><p>Definition of large depends on the underlying probabilities (odds)</p></li>
<li><p>Recall the rule of thumb for chi-squared tests based on the expected number of events</p></li>
</ul></li>
<li><p>Assumption 2: Assumptions about the independence of observations</p>
<ul>
<li><p>Classical regression: Independence of all observation</p></li>
<li><p>Robust standard errors: Correlated observations within identified clusters</p></li>
<li><p>Assumption 3: Assumptions about variance of observations within groups</p></li>
</ul></li>
<li><p>Classical regression: Mean-variance relationship for binary data</p>
<ul>
<li><p>Classical logistic regression estimates SE using model based estimates</p></li>
<li><p>Hence in order to satisfy this requirement, linearity of log odds across groups must hold</p></li>
</ul></li>
<li><p>Robust standard errors</p>
<ul>
<li><p>Allows unequal variance across groups</p></li>
<li><p>Hence, do not need linearity of log odds across groups to hold</p></li>
<li><p>Valid statistical inference (CIs, p-values) about <em>odds of response in specific groups</em> requires a further assumption</p></li>
</ul></li>
<li><p>Assumption 4: Adequacy of the linear model</p>
<ul>
<li><p>If we are trying to borrow information about the log odds from neighboring groups, and we are assuming a straight line relationship, the straight line needs to be true</p></li>
<li><p>Needed for either classical or robust standard errors</p></li>
<li><p>Note that we can model transformations of the measured predictor if we feel a straight line is not appropriate</p></li>
<li><p>Inference about <em>individual observations</em> (prediction intervals, P-values) in specific groups requires no further assumptions because we have binary data</p>
<ul>
<li><p>For binary data, if we know the mean (proportion), we know everything about the distribution including the variance</p></li>
<li><p>This differs from linear regression where we can have a correct model for the mean, but the assumption about the error distribution (Normality, homoskedasticity) can be incorrect</p></li>
</ul></li>
</ul></li>
</ul>
<section id="interpreting-positive-results" class="level3" data-number="4.1">
<h3 data-number="4.1" class="anchored" data-anchor-id="interpreting-positive-results"><span class="header-section-number">4.1</span> Interpreting “Positive” Results</h3>
<ul>
<li><p>Slope is statistically different from 0 using robust standard errors</p></li>
<li><p>Observed data is atypical of a setting with no linear trend in odds of response across groups</p></li>
<li><p>Data suggests evidence of a trend toward larger (or smaller) odds in groups having larger values of the predictor</p></li>
<li><p>(To the extent the data appears linear, estimates of the group odds or probabilities will be reliable)</p></li>
</ul>
</section>
<section id="interpreting-negative-results" class="level3" data-number="4.2">
<h3 data-number="4.2" class="anchored" data-anchor-id="interpreting-negative-results"><span class="header-section-number">4.2</span> Interpreting “Negative” Results</h3>
<ul>
<li><p>Many possible reasons why the slope is not statistically different from 0 using robust standard errors</p>
<ul>
<li><p>There may be no association between the response and predictor</p></li>
<li><p>There may be an association in the parameter considered, but the best fitting line has zero slope</p></li>
<li><p>There may be a first order trend in the log odds, but we lacked the precision to be confident that it truly exists (a type II error)</p></li>
</ul></li>
</ul>
</section>
</section>
<section id="example-analysis-revisited-effect-modification" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="example-analysis-revisited-effect-modification"><span class="header-section-number">5</span> Example analysis revisited: Effect Modification</h2>
<ul>
<li><p>Recall in our Titanic example that the effect of age appeared to differ by sex</p>
<ul>
<li><p>We ignored this difference earlier, so our estimated age effect was a (weighted) average of the age effect in males and the age effect in female</p></li>
<li><p>Here is the plot again describing the trends we see in survival by age and sex (using plsmo).</p></li>
</ul></li>
</ul>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="co"># | fig-cap: Age versus survival by gender in the Titanic data by age using a super smoother.</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a><span class="fu">with</span>(titanic, </span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>     <span class="fu">plsmo</span>(age, survived, <span class="at">group=</span>sex, <span class="at">datadensity=</span>T, <span class="at">ylab=</span><span class="st">"Survived (1=Yes, 0=No)"</span>, <span class="at">xlab=</span><span class="st">"Age (years)"</span>)</span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="Lec04.Logistic_files/figure-html/unnamed-chunk-26-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<ul>
<li><p>We could describe the observed differences in two way, both being correct</p></li>
<li><p>Gender modifies the age effect</p>
<ul>
<li>In males, the probability of survival worsened with age while in female the probabilty of survival improved with age</li>
<li>Emphasizes that the female age slope is positive while the male age slope is negative</li>
</ul></li>
<li><p>Age modifies the gender effect</p>
<ul>
<li>The survival rates of male and females were more similar at younger ages than older ages</li>
<li>Could specify the odds ratio of survival comparing females to males at specific ages</li>
</ul></li>
</ul>
<section id="stratified-analysis-by-sex" class="level3" data-number="5.1">
<h3 data-number="5.1" class="anchored" data-anchor-id="stratified-analysis-by-sex"><span class="header-section-number">5.1</span> Stratified analysis by sex</h3>
<ul>
<li>The log odds of survival in females</li>
</ul>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>fit.titanic.female <span class="ot">&lt;-</span> <span class="fu">glm</span>(survived <span class="sc">~</span> age, <span class="at">data=</span>titanic, <span class="at">subset=</span>sex<span class="sc">==</span><span class="st">"female"</span>)</span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>fit.titanic.female</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:  glm(formula = survived ~ age, data = titanic, subset = sex == 
    "female")

Coefficients:
(Intercept)          age  
   0.637644     0.004006  

Degrees of Freedom: 387 Total (i.e. Null);  386 Residual
  (78 observations deleted due to missingness)
Null Deviance:      72.25 
Residual Deviance: 70.93    AIC: 447.7</code></pre>
</div>
</div>
<ul>
<li>The log odds of survival in males</li>
</ul>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>fit.titanic.male <span class="ot">&lt;-</span> <span class="fu">glm</span>(survived <span class="sc">~</span> age, <span class="at">data=</span>titanic, <span class="at">subset=</span>sex<span class="sc">==</span><span class="st">"male"</span>)</span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>fit.titanic.male</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:  glm(formula = survived ~ age, data = titanic, subset = sex == 
    "male")

Coefficients:
(Intercept)          age  
   0.316337    -0.003635  

Degrees of Freedom: 657 Total (i.e. Null);  656 Residual
  (185 observations deleted due to missingness)
Null Deviance:      107.3 
Residual Deviance: 105.5    AIC: 669.1</code></pre>
</div>
</div>
<section id="odds-ratios-and-confidence-intervals-for-age-effect-by-sex" class="level4" data-number="5.1.1">
<h4 data-number="5.1.1" class="anchored" data-anchor-id="odds-ratios-and-confidence-intervals-for-age-effect-by-sex"><span class="header-section-number">5.1.1</span> Odds ratios and confidence intervals for age effect by sex</h4>
<ul>
<li>Consider a 5 year change in age</li>
</ul>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Females</span></span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(<span class="dv">5</span><span class="sc">*</span><span class="fu">coef</span>(fit.titanic.female)[<span class="st">"age"</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>     age 
1.020234 </code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(<span class="dv">5</span><span class="sc">*</span><span class="fu">confint.default</span>(fit.titanic.female,<span class="st">"age"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>       2.5 %  97.5 %
age 1.005398 1.03529</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Males</span></span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(<span class="dv">5</span><span class="sc">*</span><span class="fu">coef</span>(fit.titanic.male)[<span class="st">"age"</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>      age 
0.9819903 </code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(<span class="dv">5</span><span class="sc">*</span><span class="fu">confint.default</span>(fit.titanic.male,<span class="st">"age"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>        2.5 %    97.5 %
age 0.9715019 0.9925919</code></pre>
</div>
</div>
</section>
</section>
<section id="effect-modification-using-interaction-terms" class="level3" data-number="5.2">
<h3 data-number="5.2" class="anchored" data-anchor-id="effect-modification-using-interaction-terms"><span class="header-section-number">5.2</span> Effect modification using interaction terms</h3>
<ul>
<li>Instead of fitting two seaparte models for male and females, we could estimate all parameters in a single regression model
<ul>
<li>Let <span class="math inline">\(p_i\)</span> be the probability of survival for passenger <span class="math inline">\(i\)</span> and <span class="math inline">\(\textrm{logit}(p)= \textrm{log}\left(\frac{p}{1-p}\right)\)</span></li>
<li>Let <span class="math inline">\(X_{1i}\)</span> be the age of subject <span class="math inline">\(i\)</span></li>
<li>Let <span class="math inline">\(X_{2i}\)</span> be an indicator variable for female sex. <span class="math inline">\(X_{2i}=1\)</span> if a subject is female and <span class="math inline">\(X_{2i} = 0\)</span> if a subject is male</li>
</ul></li>
</ul>
<p><span class="math display">\[\textrm{logit}(p | X_{1i},X_{2i}) = \beta_0 + \beta_1 * X_{1i} + \beta_{2i} * X_{2i} + \beta_3*X_{1i}*X_{2i}\]</span></p>
<ul>
<li>In males, <span class="math inline">\(X_{2i} = 0\)</span>, this model reduces to</li>
</ul>
<p><span class="math display">\[\textrm{logit}(p | X_{1i}, X_{2i}=0) = \beta_0 + \beta_1 * X_{1i}\]</span></p>
<ul>
<li>In females, <span class="math inline">\(X_{2i} = 1\)</span>, this model can be expressed as</li>
</ul>
<p><span class="math display">\[\textrm{logit}(p | X_{1i}, X_{2i}=1) = (\beta_0+\beta_2) + (\beta_1+\beta_3) * X_{1i}\]</span></p>
<ul>
<li><span class="math inline">\(\hat{\beta_1}\)</span> is the estimate age effect in males</li>
<li><span class="math inline">\(\hat{\beta_1} + \hat{\beta_3}\)</span> is the estimated age effect in females</li>
<li><span class="math inline">\(\hat{\beta_3}\)</span> is the estimated <em>difference</em> between the age effect in male and the age effect in females</li>
</ul>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="co"># female has already been defined in the dataset, but if I wanted to create this variable I could do so</span></span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a>titanic<span class="sc">$</span>female <span class="ot">&lt;-</span> (titanic<span class="sc">$</span>sex<span class="sc">==</span><span class="st">"female"</span>)<span class="sc">+</span><span class="dv">0</span></span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-4"><a href="#cb49-4" aria-hidden="true" tabindex="-1"></a>fit.titanic.interact <span class="ot">&lt;-</span> <span class="fu">glm</span>(survived <span class="sc">~</span> age <span class="sc">+</span> female <span class="sc">+</span> age<span class="sc">*</span>female, <span class="at">data=</span>titanic)</span>
<span id="cb49-5"><a href="#cb49-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit.titanic.interact)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = survived ~ age + female + age * female, data = titanic)

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  0.316337   0.037944   8.337 2.39e-16 ***
age         -0.003635   0.001124  -3.233  0.00126 ** 
female       0.321307   0.059757   5.377 9.35e-08 ***
age:female   0.007641   0.001823   4.192 3.01e-05 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for gaussian family taken to be 0.1693472)

    Null deviance: 252.69  on 1045  degrees of freedom
Residual deviance: 176.46  on 1042  degrees of freedom
  (263 observations deleted due to missingness)
AIC: 1116.9

Number of Fisher Scoring iterations: 2</code></pre>
</div>
</div>
<ul>
<li>We can see that the parameter estimates from the interaction model are the same as the estimates from the two stratified models</li>
</ul>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Interaction model</span></span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(fit.titanic.interact)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code> (Intercept)          age       female   age:female 
 0.316337448 -0.003634770  0.321306890  0.007641206 </code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Model fit just on male subjects</span></span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(fit.titanic.male)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>(Intercept)         age 
 0.31633745 -0.00363477 </code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Model fit just on female subjects</span></span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(fit.titanic.female)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>(Intercept)         age 
0.637644338 0.004006436 </code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Linear combinations from the interaction model give the female intercept and age slope</span></span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(fit.titanic.interact)[<span class="dv">1</span>] <span class="sc">+</span> <span class="fu">coef</span>(fit.titanic.interact)[<span class="dv">3</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>(Intercept) 
  0.6376443 </code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(fit.titanic.interact)[<span class="dv">2</span>] <span class="sc">+</span> <span class="fu">coef</span>(fit.titanic.interact)[<span class="dv">4</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>        age 
0.004006436 </code></pre>
</div>
</div>


<!-- -->

</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  let localAlternateSentinel = 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } 
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    setTimeout(function() {
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  const viewSource = window.document.getElementById('quarto-view-source') ||
                     window.document.getElementById('quarto-code-tools-source');
  if (viewSource) {
    const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
    viewSource.addEventListener("click", function(e) {
      if (sourceUrl) {
        // rstudio viewer pane
        if (/\bcapabilities=\b/.test(window.location)) {
          window.open(sourceUrl);
        } else {
          window.location.href = sourceUrl;
        }
      } else {
        const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
        modal.show();
      }
      return false;
    });
  }
  function toggleCodeHandler(show) {
    return function(e) {
      const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
      for (let i=0; i<detailsSrc.length; i++) {
        const details = detailsSrc[i].parentElement;
        if (show) {
          details.open = true;
        } else {
          details.removeAttribute("open");
        }
      }
      const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
      const fromCls = show ? "hidden" : "unhidden";
      const toCls = show ? "unhidden" : "hidden";
      for (let i=0; i<cellCodeDivs.length; i++) {
        const codeDiv = cellCodeDivs[i];
        if (codeDiv.classList.contains(fromCls)) {
          codeDiv.classList.remove(fromCls);
          codeDiv.classList.add(toCls);
        } 
      }
      return false;
    }
  }
  const hideAllCode = window.document.getElementById("quarto-hide-all-code");
  if (hideAllCode) {
    hideAllCode.addEventListener("click", toggleCodeHandler(false));
  }
  const showAllCode = window.document.getElementById("quarto-show-all-code");
  if (showAllCode) {
    showAllCode.addEventListener("click", toggleCodeHandler(true));
  }
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const cites = ref.parentNode.getAttribute('data-cites').split(' ');
    tippyHover(ref, function() {
      var popup = window.document.createElement('div');
      cites.forEach(function(cite) {
        var citeDiv = window.document.createElement('div');
        citeDiv.classList.add('hanging-indent');
        citeDiv.classList.add('csl-entry');
        var biblioDiv = window.document.getElementById('ref-' + cite);
        if (biblioDiv) {
          citeDiv.innerHTML = biblioDiv.innerHTML;
        }
        popup.appendChild(citeDiv);
      });
      return popup.innerHTML;
    });
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../notes/Lec03.SimpleLinearRegression.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">Simple Linear Regression</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../notes/Lec05.Precision.html" class="pagination-link">
        <span class="nav-page-text">Precision of Statistical Intefence</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<pre class="markdown" data-shortcodes="false"><code>---
title: "Logistic Regression"
subtitle: "Lecture 04"
author: "Chris Slaughter"
footer: "Bios 6312"
format:
  html:
    number-sections: true
    number-depth: 4
    anchor-sections: true
    smooth-scroll: true
    theme: journal
    toc: true
    toc-depth: 4
    toc-title: Contents
    toc-location: left
    code-link: false
    code-tools: true
    code-fold: true
    code-block-bg: "#f1f3f5"
    code-block-border-left: "#31BAE9"
    reference-location: margin
    fig-cap-location: margin
    fontsize: medium
execute:
   warning: false
   message: false
editor: 
  markdown: 
    wrap: 72
---

## General Regression Setting

-   Types of variables

    -   Binary data: e.g. sex, death

    -   Nominal (unordered categorical) data: e.g. race, martial status

    -   Ordinal (ordered categorical data): e.g. cancer stage, asthma
        severity

    -   Quantitative data: e.g. age, blood pressure

    -   Right censored data: e.g. time to death

-   The measures used to summarize and compare distributions vary
    according to the type of variable

    -   Means: Binary, quantitative

    -   Medians: Ordered, quantitative, censored

    -   Proportions: Binary, nominal, ordinal

    -   Odds: Binary, nominal, ordinal

    -   Hazards: Censored

-   Which regression model you choose to use is based on the parameter
    being compared across groups

::: center
| Parameter       | Approach                              |
|:----------------|:--------------------------------------|
| Means           | Linear regression                     |
| Geometric means | Linear regression on log scale        |
| Odds            | Logistic regression                   |
| Rates           | Poisson regression                    |
| Hazards         | Proportional Hazards (Cox) regression |
:::

-   General notation for variables and parameters

::: center
|            |                                                      |
|:-----------|:-----------------------------------------------------|
| $Y_i$      | Response measured on the $i$th subject               |
| $X_i$      | Value of the predictor measured on the $i$th subject |
| $\theta_i$ | Parameter summarizing distribution of $Y_i | X_i$    |
:::

-   The parameter ($\theta_i$) might be the mean, geometric mean, odds,
    rate, instantaneous risk of an event (hazard), etc.

-   In linear regression on means, $\theta_i = E[Y_i | X_i]$

-   Choice of correct $\theta_i$ should be based on scientific
    understanding of problem

-   General notation for simple regression model

$$g(\theta_i) = \beta_0 + \beta_1 \times X_i$$

::: center
General notation for regression model with one predictor

|           |                                 |
|:----------|:--------------------------------|
| $g( )$    | Link function used for modeling |
| $\beta_0$ | Intercept                       |
| $\beta_1$ | Slope for predictor $X$         |
:::

-   The link function is often either the identity function (for
    modeling means) or log (for modeling geometric means, odds, hazards)

    -   Identity function: $f(x) = x$

### Uses of General Regression

-   Borrowing information

    -   Use other groups to make estimates in groups with sparse data

    -   Intuitively, 67 and 69 year olds would provide some relevant
        information about 68 year olds

    -   Assuming a straight line relationship tells us about other, even
        more distant, individuals

    -   If we do not want to assume a straight line, we may only want to
        borrow information from nearby groups

-   Defining "Contrasts"

    -   Define a comparison across groups to use when answering
        scientific questions

    -   If the straight line relationship holds, the slope is the
        difference in parameter between groups differing by 1 unit in
        $X$

    -   If a non-linear relationship in parameter, the slope is still
        the average difference in parameter between groups differing by
        1 unit in $X$

    -   Slope is a (first order or linear) test for trend in the
        parameter

    -   Statistical jargon: "a contrast" across groups

-   The major difference between different regression models is the
    interpretation of the parameters

    -   How do I want to summarize the outcome?

    -   Mean, geometric mean, odds, hazard

-   How do I want to compare groups?

    -   Difference, ratio

-   Answering these two simple questions provides a starting road-map as
    to which regression model to choose

-   Issues related to the inclusion of covariates remains the same

    -   Address the scientific question: Predictor of interest, effect
        modification

    -   Address confounding

    -   Increase precision

## Simple Logistic Regression

### Uses of logistic regression

-   Use logistic regression when you want to make inference about the
    odds

    -   Allows for continuous (or multiple) grouping variables

    -   Is OK with binary grouping variables too

    -   Compares odds of responses across groups using ratios

        -   "Odds ratio"

-   Binary response variable

-   When using regression with binary response variables, we typically
    model the (log) odds using logistic regression

    -   Conceptually there should be no problem modeling the proportion
        (which is the mean of the distribution)

    -   However, there are several technical reasons why we do not use
        linear regression very often with binary responses

    -   Why not use linear regression for binary responses?

-   Many misconceptions about the advantages and disadvantages of
    analyzing the odds

    -   Reasons I consider valid: Scientific basis

        -   Uses of odds ratios in case control studies

        -   Plausibility of linear trends and no effect modifiers

    -   Reasons I consider valid: Statistical basis

        -   There is a mean variance relationship (if not using robust
            SE) that can be incorporate in the logistic regression model

### Reasons to use logistic regression

-   First (scientific) reason: Case-Control Studies

    -   Studying a rare disease, so we do study in reverse

        -   e.g. find subjects with cancer (and suitable controls) and
            then ascertain exposure of interest

        -   Estimate distribution of the "effect" across groups defined
            by "cause"

        -   Proportion (or odds) of smokers among people with or without
            lung cancer

    |            |               |               |
    |------------|---------------|---------------|
    |            | Lung Cancer + | Lung Cancer - |
    | Smoker     | a             | b             |
    | Non-Smoker | c             | d             |

    : Case-Control or Cohort 2x2 Table. In the Case-Control design, the
    total number of subjects with Cancer $(a+c)$ and without cancer
    $(b+d)$ are fixed by design.

    -   In contrast, a cohort study samples by exposure (smoking) and
        then estimates the distribution of the effect in exposure groups

    -   In a case-control study, we cannot estimate prevalence (without
        knowing selection probabilities)

        -   e.g. if doing a 1:1 case-control study, $(a+c) = b+d$ so it
            would look like $50\%$ of the subjects have cancer

    -   Odds ratios are estimable in either case-control or cohort
        sampling scheme

        -   Cohort study: Odds of cancer among smoker compared to odds
            of cancer among nonsmokers

        -   Case-control study: Odds of smoking among cancer compared to
            odds of smoking among non-cancer

    -   Mathematically, these two odds ratios are the same

        -   

    -   Odds ratios are easy to interpret when investigating rare events

        -   Odds = prob / (1 - prob)

        -   For rare events, (1 - prob) is approximately 1

            -   Odds is approximately the probability

            -   Odds ratios are approximately risk ratios

        -   Case-control studies usually used when events are rare

-   Second (scientific) reason: Linearity

    -   Proportions are bounded by 0 and 1

    -   It is thus unlikely that a straight line relationship would
        exists between a proportion and a predictor

        -   Unless the predictor itself is bounded

        -   Otherwise, there eventually must be a threshold above which
            the probability does not increase (or only increases a
            little)

quarto-executable-code-5450563D

```r
#| fig-cap: Logistic function will bound probabilities between 0 and 1
expit &lt;- function(x) {exp(x)/(1+exp(x))}
plot(function(x) expit(x), -4,4, ylab="Probabilty", xlab="Predictor")
```

-   Third (scientific) reason: Effect modification

    -   The restriction on ranges for probabilities makes it likely that
        effect modification *must* be present with proportions

    -   Example: Is the association between 2-year relapse rates and
        having a positive scan modified by gender?

        -   Women relapse 40% of the time when the scan is negative, and
            95% of the time when the scan is positive (an increase of
            55%)

            -   If men relapse 75% of the time when the scan is
                negative, then a positive scan can increase the relapse
                rate to at most 100%, which is only a 25% increase

                |                 |       |              |
                |-----------------|-------|--------------|
                | **Proportions** |       |              |
                |                 | Women | Men          |
                | Negative Scan   | 40%   | 75%          |
                | Positive Scan   | 95%   | (up to 100%) |
                |                 |       |              |
                | Difference      | 55%   | Up to 25%    |
                | Ratio           | 1.64  | $\leq 1.33$  |

            -   With the odds, the association can hold without effect
                modification

                |               |       |                  |
                |---------------|-------|------------------|
                | **Odds**      |       |                  |
                |               | Women | Men              |
                | Negative Scan | 0.67  | 3                |
                | Positive Scan | 19    | (up to $\infty$) |
                |               |       |                  |
                | Ratio         | 28.5  | $&lt; \infty$       |

-   If the o dds of positive scan in men was 85.5, then the odds ratio
    would be exactly 28.5 (no effect modification)

-   Fourth (statistics) reason:

    -   Classical linear regression requires equal variances across each
        predictor group

    -   But, with binary data, the variance within a group depends on
        the mean

    -   For binary $Y$, $E(Y) = p$ and $Var(Y) = p(1-p)$

    -   With robust standard errors, the mean-variance relationship is
        not a major problem. However, a logistic model that correctly
        models the mean-variance relationship will be more efficient.

### The simple logistic regression model

-   Modeling the odds of binary response variable $Y$ on predictor $X$

    -   Distribution: $\textrm{Pr}(Y_i = 1) = p_i$

    -   Model:
        $\textrm{logit}(p_i) = \textrm{log}\left(\frac{p_i}{1-p_i}\right) = \beta_0 + \beta_1 \times X_i$

    -   When $X_i = 0$: log odds = $\beta_0$

    -   When $X_i = x$: log odds = $\beta_0 + \beta_1 \times x$

    -   When $X_i = x+1$: log odds =
        $\beta_0 + \beta_1 \times x + \beta_1$

-   To interpret as odds, exponentiate the regression parameters

    -   Distribution: $\textrm{Pr}(Y_i = 1) = p_i$
    -   Model:
        $\frac{p_i}{1-p_i} = \exp(\beta_0 + \beta_1 \times X_i) = e^{\beta_0} \times e^{\beta_1 \times X_i}$
    -   When $X_i = 0$: odds = $e^{\beta_0}$
    -   When $X_i = x$: odds = $e^{\beta_0} \times e^{\beta_1 \times x}$
    -   When $X_i = x+1$: odds =
        $e^{\beta_0} \times e^{\beta_1 \times x} \times e^{\beta_1}$

-   To interpret as proportions (remember proportion = odds / (1 +
    odds))

    -   Distribution: $\textrm{Pr}(Y_i = 1) = p_i$
    -   Model:
        $p_i = \frac{e^{\beta_0} e^{\beta_1 \times X_i}}{1 + e^{\beta_0} e^{\beta_1 \times X_i}}$
    -   When $X_i = 0$: $p_i = \frac{e^{\beta_0}}{1 + e^{\beta_0}}$\
    -   When $X_i = x$:
        $p_i = \frac{e^{\beta_0} e^{\beta_1 \times x}}{1 + e^{\beta_0} e^{\beta_1 \times x}}$
    -   When $X_i = x+1$:
        $p_i = \frac{e^{\beta_0} e^{\beta_1 \times x} e^{\beta_1}}{1 + e^{\beta_0} e^{\beta_1 \times x}e^{\beta_1}}$

-   Most common interpretations found by exponentiating the coefficients

    -   Odds when predictor is 0 found by exponentiating the intercept:
        $\exp(\beta_0)$

    -   Odds ratio between groups differing in the values of the
        predictor by 1 unit found by exponentiating the slope:
        $\exp(\beta_1)$

-   Stata commands

    ``` stata
    logit respvar predvar, [robust]
    ```

    -   Provides regression parameter estimates an inference on the log
        odds scale (both coefficients with CIs, SEs, p-values)

    ``` stata
    logistic respvar predvar, [robust]
    ```

    -   Provides regression parameter estimates and inference on the
        odds ratio scale (only slope with CIs, SEs, p-values)

-   R Commands

    -   With rms package, `lrm(respvar ~ predvar, ...)`

    -   In general, `glm(respvar ~ predvar, family=“binomial”)`

## Example: Survival on the Titanic and Age

-   Dataset at &lt;https://biostat.app.vumc.org/DataSets&gt;

-   Describes the survival status of individual passengers on the
    Titanic

-   Data on age available for many, but not all, subjects (data
    continually being updated)

-   Response variables is Survival

    -   Binary variable: 1=Survived, 0=Died

-   Predictor variable is Age

    -   Continuous grouping variable

-   Possibly different age effects by sex (effect modification by sex)

### Descriptive Plots

quarto-executable-code-5450563D

```r
# | fig-cap: Missing data patterns in the Tianic dataset
library(rms)
titanic &lt;- read.csv(file="data/titanic3.csv")
plot(naclus(titanic)) # study patterns of missing values
```

quarto-executable-code-5450563D

```r
# | fig-cap: Scatterplot of age versus survival in the Titanic data with lowess smooth.  This simple plot is not very useful because survival is either 0 or 1, making it hard to visualize any trends.
ggplot(titanic, aes(x=age, y=survived)) + geom_jitter(width=0, height=.02, alpha=.5) + geom_smooth()
```

quarto-executable-code-5450563D

```r
# | fig-cap: Age versus survival by sex in the Titanic data by age using a super smoother.  The trends are clearer with this smoothing approach.
with(titanic, 
     plsmo(age, survived, group=sex, datadensity=T, ylab="Survived (1=Yes, 0=No)", xlab="Age (years)")
)
```

quarto-executable-code-5450563D

```r
```

-   Comments on the plots

    -   Age is missing for many subjects, which we will not worry about
        in the following analysis

    -   The simple scatterplot, even with superimposes lowess smooth, is
        worthless. I have jittered the point and altered their opacity
        to help visualize overlapping point.

    -   More advanced plotting available in R (in this case, the plsmo()
        function) can help to visualize the data

### Regression Model

-   Regression model for survival on age (ignoring possible effect
    modification for now)

-   Answer question by assessing linear trends in log odds of survival
    by age

-   Estimate the best fitting line to log odds of survival within age
    groups

$$\textrm{logodds}(\textrm{Survival} | \textrm{Age}) = \beta_0 + \beta_1 \times \textrm{Age}$$

-   An association will exist if the slope $\beta_1$ is nonzero

-   In that case, the odds (and probability) of survival will be
    different across different age groups

quarto-executable-code-5450563D

```r
m.titanic &lt;- glm(survived ~ age, data=titanic, family = "binomial")
summary(m.titanic)
```

$\textrm{logodds}(\textrm{Survival} | \textrm{Age}) = -0.1365 - 0.007899 \times \textrm{Age}$

-   General interpretation

    -   Intercept is labeled "(Intercept)"

    -   Slope for age is labeled "age"

-   Interpretation of intercept

    \*Estimated log odds for newborns (age=0) is $-0.136534$

    -   Odds of survival for newborns is $e^{-0.136534} = 0.8724$

    -   Probability of survival

        -   Prob = odds / (1 + odds)

        -   $0.8724 / (1 + .8724) = 0.4659$

quarto-executable-code-5450563D

```r
predict(m.titanic, newdata=data.frame(age=0), type='response')
```

-   Interpretation of slope

    -   Estimate difference in the log odds of survival for two groups
        differing by one year in age is $-0.0078985$

    -   This estimate averages over males and females

    -   Older groups tend to have lower log odds

    -   Odds Ratio: $e^{-0.0078985} = 0.9921$

    -   For five year difference in age:
        $e^{-0.0078985 \times 5} = 0.9612$

    -   In Stata use "lincom age, or" or "lincom 5\*age, or"

Note that if the straight line relationship does not hold true, we
interpret the slope as an average difference in the log odds of survival
per one year difference in age

There are several ways to get the odds ratio and confidence interval in
R

quarto-executable-code-5450563D

```r
# The coefficient and confidence interval (on the log-odds scale)
coef(m.titanic)["age"]
confint.default(m.titanic, "age")

# Odds ratio for age and confidence interval for age (1 year increase)
exp(coef(m.titanic)["age"])
exp(confint.default(m.titanic, "age"))


# Odds ratio for age and confidence interval for age (5 year increase)
exp(5*coef(m.titanic)["age"])
exp(5*confint.default(m.titanic, "age"))
```

-   Using finalfit to create a nicer output table of the coefficients
    and confidence intervals

    -   For finalfit to use a logistic regression model by default,
        survived must be defined as a factor variable with two levels

quarto-executable-code-5450563D

```r
mykable = function(x){
  knitr::kable(x, row.names = FALSE, align = c("l", "l", "r", "r", "r", "r", "r", "r", "r"),
               booktabs=TRUE)
}


library(finalfit)
library(dplyr)
library(rms)
explanatory = c("age")

titanic$survived.factor &lt;- factor(titanic$survived, levels=0:1, labels=c("Died","Survived"))
dependent = 'survived.factor'

label(titanic$age) &lt;- "Age (years)"
titanic %&gt;% 
  finalfit(dependent, explanatory) %&gt;% mykable()

```

### Comments on Interpretation

-   The slope for age is expressed as a difference in group means, not
    the difference due to aging. We did not do a longitudinal study in
    which repeated measurements were taken on the same subject.

-   If the group log odds are truly linear, then the slope has an exact
    interpretation as the change in survival due to a one year change in
    (any) age

-   Otherwise, the slope estimates the first order trend of the sample
    data and we should not treat the estimates of group odds or
    probabilities as accurate

-   It is difficult to see in the above example, but the CIs around the
    odds ratios are not symmetric

    -   (Symmetric) CIs are calculated on the log odds scale, and then
        transformed to the odds scale by expoenentiating the lower and
        upper limits of the CI

-   "From logistic regression analysis, we estimate that for each 5 year
    difference in age, the odds of survival on the Titanic decreased by
    3.9%, though this estimate is not statistically significant
    ($p = 0.07$). A 95% CI suggests that this observation is not unusual
    if a group that is five years older might have an odds of survival
    that was anywhere between 7.9% lower and 0.4% higher than the
    younger group."

-   The confidence interval and statistical test given in the output is
    called a Wald test. Other tests (Score, Likelihood Ratio) are also
    possible.

    -   All tests are asymptotically equivalent

    -   The Wald test is easiest to obtain, but generally performs the
        poorest in small sample sizes

    -   The Likelihood Ratio test performs the best in small samples. We
        will discuss it later, including how to obtain the test using
        post-estimation commands.

    -   The Score test is not bad in small samples, but is often hard to
        obtain from software. It is exactly equal to the Chi-squared
        test for binary outcomes and categorical predictors.

#### Bayesian Estimates and Interpretation

-   Bayesian approach to the logistic model requires specifying

    -   The model

    -   e.g. a model for the log odds of survival that is linear in the
        parameters with an intercept and slope for age

    -   Prior distributions on parameters

        -   For the simple logistic regression model, we have parameters
            $\beta_0$, and $\beta_1$.

        -   For now, we will use default prior distributions that are
            are intended to be *weakly informative* in that they provide
            moderate regularization and help stabilize computation. See
            the [STAN
            documentation](https://mc-stan.org/rstanarm/reference/priors.html)
            for more details

        -   Appropriate priors can be based on scientific considerations

        -   Sensitivity analyses can evaluate the the robustness of
            finding to different prior assumptions

-   The likelihood

    -   For a binomial GLM the likelihood for one observation $y$ can be
        written as a conditionally binomial probability mass function

$$\binom{n}{y} \pi^{y} (1 - \pi)^{n - y},$$

-   $n$ is the known number of trials, $\pi = g^{-1}(\eta)$ is the
    probability of success and
    $\eta = \alpha + \mathbf{x}^\top \boldsymbol{\beta}$ is a linear
    predictor

-   For a sample of size $N$, the likelihood of the entire sample is the
    product of $N$ individual likelihood contributions.

-   Because $\pi$ is a probability, for a binomial model the *link*
    function $g$ maps between the unit interval (the support of $\pi$)
    and the set of all real numbers $\mathbb{R}$. When applied to a
    linear predictor $\eta$ with values in $\mathbb{R}$, the inverse
    link function $g^{-1}(\eta)$ therefore returns a valid probability
    between 0 and 1.

-   The two most common link functions used for binomial GLMs are the

    -   [logit](https://en.wikipedia.org/wiki/Logit) and
    -   [probit](https://en.wikipedia.org/wiki/Probit)

-   With the logit (or log-odds) link function
    $g(x) = \ln{\left(\frac{x}{1-x}\right)}$, the likelihood for a
    single observation becomes

$$\binom{n}{y}\left(\text{logit}^{-1}(\eta)\right)^y 
\left(1 - \text{logit}^{-1}(\eta)\right)^{n-y} = 
\binom{n}{y} \left(\frac{e^{\eta}}{1 + e^{\eta}}\right)^{y}
\left(\frac{1}{1 + e^{\eta}}\right)^{n - y}$$

-   With the probit link function $g(x) = \Phi^{-1}(x)$ yields the
    likelihood

$$\binom{n}{y} \left(\Phi(\eta)\right)^{y}
\left(1 - \Phi(\eta)\right)^{n - y},$$

where $\Phi$ is the CDF of the standard normal distribution.

-   Output from Bayesian logistic regression using logit link function

quarto-executable-code-5450563D

```r
library(rstanarm)
library(bayesplot)

fit2 &lt;- stan_glm(survived ~ age,
                 data=titanic, family=binomial(),
                 seed=1234,
                 refresh=0)
summary(fit2, digits=4, prob=c(.025, .5, .975))
```

-   And a summary of the prior distributions used

quarto-executable-code-5450563D

```r
prior_summary(fit2, digits = 2)
```

-   Interpretation

    -   Slope for age is of primary scientific importance

    -   *A priori* we assume that no association between age and
        cholesterol. Specifically, we assumed a Normal prior with
        location (mean) of 0 and scale (standard devation) of 0.17 for
        $\beta_1$.

    -   Conditional on the data, we estimate that for every 1 year
        increase in age, the log odds of decreases by -0.0079 (95%
        credible interval -0.0169 to 0.0004).

    -   To obtain the posterior odds ratio and 95% credible intervals,
        some additional commands are needed

quarto-executable-code-5450563D

```r
# 1 year change in age
exp(coef(fit2)["age"]) # Posterior Odds Ratio
exp(posterior_interval(fit2, prob = 0.95)) # 95% credible interval

# 5 year change in age
exp(5*coef(fit2)["age"]) # Posterior Odds Ratio
exp(5*posterior_interval(fit2, prob = 0.95))[2,] # 95% credible interval


```

## Inference with Logistic Regression

-   The ideas of Signal and Noise found in simple linear regression do
    not translate well to logistic regression

-   We do not tend to quantify an error distribution with logistic
    regression

-   Valid statistical inference (CIs, p-values) about *associations*
    requires three general assumptions

-   Assumption 1: Approximately Normal distributions for the parameter
    estimates

    -   Large N

    -   Need for either robust standard errors or classical logistic
        regression

    -   Definition of large depends on the underlying probabilities
        (odds)

    -   Recall the rule of thumb for chi-squared tests based on the
        expected number of events

-   Assumption 2: Assumptions about the independence of observations

    -   Classical regression: Independence of all observation

    -   Robust standard errors: Correlated observations within
        identified clusters

    -   Assumption 3: Assumptions about variance of observations within
        groups

-   Classical regression: Mean-variance relationship for binary data

    -   Classical logistic regression estimates SE using model based
        estimates

    -   Hence in order to satisfy this requirement, linearity of log
        odds across groups must hold

-   Robust standard errors

    -   Allows unequal variance across groups

    -   Hence, do not need linearity of log odds across groups to hold

    -   Valid statistical inference (CIs, p-values) about *odds of
        response in specific groups* requires a further assumption

-   Assumption 4: Adequacy of the linear model

    -   If we are trying to borrow information about the log odds from
        neighboring groups, and we are assuming a straight line
        relationship, the straight line needs to be true

    -   Needed for either classical or robust standard errors

    -   Note that we can model transformations of the measured predictor
        if we feel a straight line is not appropriate

    -   Inference about *individual observations* (prediction intervals,
        P-values) in specific groups requires no further assumptions
        because we have binary data

        -   For binary data, if we know the mean (proportion), we know
            everything about the distribution including the variance

        -   This differs from linear regression where we can have a
            correct model for the mean, but the assumption about the
            error distribution (Normality, homoskedasticity) can be
            incorrect

### Interpreting "Positive" Results

-   Slope is statistically different from 0 using robust standard errors

-   Observed data is atypical of a setting with no linear trend in odds
    of response across groups

-   Data suggests evidence of a trend toward larger (or smaller) odds in
    groups having larger values of the predictor

-   (To the extent the data appears linear, estimates of the group odds
    or probabilities will be reliable)

### Interpreting "Negative" Results

-   Many possible reasons why the slope is not statistically different
    from 0 using robust standard errors

    -   There may be no association between the response and predictor

    -   There may be an association in the parameter considered, but the
        best fitting line has zero slope

    -   There may be a first order trend in the log odds, but we lacked
        the precision to be confident that it truly exists (a type II
        error)

## Example analysis revisited: Effect Modification

-   Recall in our Titanic example that the effect of age appeared to
    differ by sex

    -   We ignored this difference earlier, so our estimated age effect
        was a (weighted) average of the age effect in males and the age
        effect in female

    -   Here is the plot again describing the trends we see in survival
        by age and sex (using plsmo).

quarto-executable-code-5450563D

```r
# | fig-cap: Age versus survival by gender in the Titanic data by age using a super smoother.
with(titanic, 
     plsmo(age, survived, group=sex, datadensity=T, ylab="Survived (1=Yes, 0=No)", xlab="Age (years)")
)
```

-   We could describe the observed differences in two way, both being
    correct

-   Gender modifies the age effect

    -   In males, the probability of survival worsened with age while in
        female the probabilty of survival improved with age
    -   Emphasizes that the female age slope is positive while the male
        age slope is negative

-   Age modifies the gender effect

    -   The survival rates of male and females were more similar at
        younger ages than older ages
    -   Could specify the odds ratio of survival comparing females to
        males at specific ages

### Stratified analysis by sex

-   The log odds of survival in females

quarto-executable-code-5450563D

```r
fit.titanic.female &lt;- glm(survived ~ age, data=titanic, subset=sex=="female")
fit.titanic.female
```

-   The log odds of survival in males

quarto-executable-code-5450563D

```r
fit.titanic.male &lt;- glm(survived ~ age, data=titanic, subset=sex=="male")
fit.titanic.male
```

#### Odds ratios and confidence intervals for age effect by sex

-   Consider a 5 year change in age

quarto-executable-code-5450563D

```r
# Females
exp(5*coef(fit.titanic.female)["age"])
exp(5*confint.default(fit.titanic.female,"age"))

# Males
exp(5*coef(fit.titanic.male)["age"])
exp(5*confint.default(fit.titanic.male,"age"))
```

### Effect modification using interaction terms

-   Instead of fitting two seaparte models for male and females, we
    could estimate all parameters in a single regression model
    -   Let $p_i$ be the probability of survival for passenger $i$ and
        $\textrm{logit}(p)= \textrm{log}\left(\frac{p}{1-p}\right)$
    -   Let $X_{1i}$ be the age of subject $i$
    -   Let $X_{2i}$ be an indicator variable for female sex. $X_{2i}=1$
        if a subject is female and $X_{2i} = 0$ if a subject is male

$$\textrm{logit}(p | X_{1i},X_{2i}) = \beta_0 + \beta_1 * X_{1i} + \beta_{2i} * X_{2i} + \beta_3*X_{1i}*X_{2i}$$

-   In males, $X_{2i} = 0$, this model reduces to

$$\textrm{logit}(p | X_{1i}, X_{2i}=0) = \beta_0 + \beta_1 * X_{1i}$$

-   In females, $X_{2i} = 1$, this model can be expressed as

$$\textrm{logit}(p | X_{1i}, X_{2i}=1) = (\beta_0+\beta_2) + (\beta_1+\beta_3) * X_{1i}$$

-   $\hat{\beta_1}$ is the estimate age effect in males
-   $\hat{\beta_1} + \hat{\beta_3}$ is the estimated age effect in
    females
-   $\hat{\beta_3}$ is the estimated *difference* between the age effect
    in male and the age effect in females

quarto-executable-code-5450563D

```r
# female has already been defined in the dataset, but if I wanted to create this variable I could do so
titanic$female &lt;- (titanic$sex=="female")+0

fit.titanic.interact &lt;- glm(survived ~ age + female + age*female, data=titanic)
summary(fit.titanic.interact)
```

-   We can see that the parameter estimates from the interaction model
    are the same as the estimates from the two stratified models

quarto-executable-code-5450563D

```r
# Interaction model
coef(fit.titanic.interact)

# Model fit just on male subjects
coef(fit.titanic.male)

# Model fit just on female subjects
coef(fit.titanic.female)

# Linear combinations from the interaction model give the female intercept and age slope
coef(fit.titanic.interact)[1] + coef(fit.titanic.interact)[3]
coef(fit.titanic.interact)[2] + coef(fit.titanic.interact)[4]
```</code></pre>
</div></div></div></div></div>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">© Copyright 2024, James C Slaughter</div>   
    <div class="nav-footer-right">This page is built with <a href="https://quarto.org/">Quarto</a>.</div>
  </div>
</footer>



<script src="../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>