{
  "hash": "ff798956434945e17039573233a53478",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Logistic Regression\"\nsubtitle: \"Lecture 04\"\nname: Lec04.Logistic.qmd\n---\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(arm)\nlibrary(Hmisc)\nlibrary(rstanarm)\nlibrary(ggplot2)\ntryCatch(source('pander_registry.R'), error = function(e) invisible(e))\n```\n:::\n\n\n\n\n## General Regression Setting\n\n-   Types of variables\n\n    -   Binary data: e.g. sex, death\n\n    -   Nominal (unordered categorical) data: e.g. race, marital status\n\n    -   Ordinal (ordered categorical data): e.g. cancer stage, asthma severity\n\n    -   Quantitative data: e.g. age, blood pressure\n\n    -   Right censored data: e.g. time to death\n\n-   The measures used to summarize and compare distributions vary according to the type of variable\n\n    -   Means: Binary, quantitative\n\n    -   Medians: Ordered, quantitative, censored\n\n    -   Proportions: Binary, nominal, ordinal\n\n    -   Odds: Binary, nominal, ordinal\n\n    -   Hazards: Censored\n\n-   Which regression model you choose to use is based on the parameter being compared across groups\n\n::: center\n| Parameter       | Approach                              |\n|:----------------|:--------------------------------------|\n| Means           | Linear regression                     |\n| Geometric means | Linear regression on log scale        |\n| Odds            | Logistic regression                   |\n| Rates           | Poisson regression                    |\n| Hazards         | Proportional Hazards (Cox) regression |\n:::\n\n-   General notation for variables and parameters\n\n::: center\n|            |                                                      |\n|:-----------|:-----------------------------------------------------|\n| $Y_i$      | Response measured on the $i$th subject               |\n| $X_i$      | Value of the predictor measured on the $i$th subject |\n| $\\theta_i$ | Parameter summarizing distribution of $Y_i \\mid X_i$    |\n:::\n\n-   The parameter ($\\theta_i$) might be the mean, geometric mean, odds, rate, instantaneous risk of an event (hazard), etc.\n\n-   In linear regression on means, $\\theta_i = E[Y_i | X_i]$\n\n-   Choice of correct $\\theta_i$ should be based on scientific understanding of problem\n\n-   General notation for simple regression model\n\n$$g(\\theta_i) = \\beta_0 + \\beta_1 \\times X_i$$\n\n::: center\nGeneral notation for regression model with one predictor\n\n|           |                                 |\n|:----------|:--------------------------------|\n| $g( )$    | Link function used for modeling |\n| $\\beta_0$ | Intercept                       |\n| $\\beta_1$ | Slope for predictor $X$         |\n:::\n\n-   The link function is often either the identity function (for modeling means) or log (for modeling geometric means, odds, hazards)\n\n    -   Identity function: $f(x) = x$\n\n### Uses of General Regression\n\n-   Borrowing information\n\n    -   Use other groups to make estimates in groups with sparse data\n\n    -   Intuitively, 67 and 69 year olds would provide some relevant information about 68 year olds\n\n    -   Assuming a straight line relationship tells us about other, even more distant, individuals\n\n    -   If we do not want to assume a straight line, we may only want to borrow information from nearby groups\n\n-   Defining \"Contrasts\"\n\n    -   Define a comparison across groups to use when answering scientific questions\n\n    -   If the straight line relationship holds, the slope is the difference in parameter between groups differing by 1 unit in $X$\n\n    -   If a non-linear relationship in parameter, the slope is still the average difference in parameter between groups differing by 1 unit in $X$\n\n    -   Slope is a (first order or linear) test for trend in the parameter\n\n    -   Statistical jargon: \"a contrast\" across groups\n\n-   The major difference between different regression models is the interpretation of the parameters\n\n    -   How do I want to summarize the outcome?\n\n    -   Mean, geometric mean, odds, hazard\n\n-   How do I want to compare groups?\n\n    -   Difference, ratio\n\n-   Answering these two simple questions provides a starting road-map as to which regression model to choose\n\n-   Issues related to the inclusion of covariates remains the same\n\n    -   Address the scientific question: Predictor of interest, effect modification\n\n    -   Address confounding\n\n    -   Increase precision\n\n\n-   The remainder of these notes will focus on logistic regression for binary outcomes\n\n    -   We will apply the general regression framework described above, where $\\theta_i$ represents the odds of the outcome and $g()$ is the logit (log odds) link function\n    \n    -   The principles of borrowing information, defining contrasts, and addressing confounding remain the same as in linear regression\n\n## Simple Logistic Regression\n\n### Uses of logistic regression\n\n-   Use logistic regression when you want to make inference about the odds\n\n    -   Allows for continuous (or multiple) grouping variables\n\n    -   Is OK with binary grouping variables too\n\n    -   Compares odds of responses across groups using ratios\n\n        -   \"Odds ratio\"\n\n-   Binary response variable\n\n-   When using regression with binary response variables, we typically model the (log) odds using logistic regression\n\n    -   Conceptually there should be no problem modeling the proportion (which is the mean of the distribution) using linear regression.  In this case, measures of associations would be the risk difference.\n\n    -   However, there are several technical reasons why we do not use linear regression very often with binary responses\n\n-   Technical problems with linear regression for binary responses:\n    \n    -   Predicted probabilities can fall outside [0,1] range\n    \n    -   Heteroskedasticity: Variance of binary outcome depends on the mean, $\\text{Var}(Y|X) = p(X)(1-p(X))$\n        \n        -   Variance is not constant across values of X\n        \n        -   Maximum variance occurs when $p=0.5$, minimum when $p$ is near 0 or 1\n        \n        -   If the scientific goal is association, less problematic with large sample size and robust SEs\n    \n    -   Non-normal residuals (also less problematic with large samples and robust SEs)\n    \n    -   Effect of predictor on probability is constrained to be linear (constant across range)\n        \n        -   A 10-year age increase has same effect on probability regardless of starting age\n        \n        -   This may be implausible when probabilities approach 0 or 1\n\n-   Why model odds instead of probabilities or risk differences?\n\n    -   Scientific basis\n    \n        -   Odds ratios are estimable in case-control studies (as shown above)\n        \n        -   Linear trends in log odds may be more plausible than linear trends in probabilities\n            \n            -   Logit transformation naturally constrains predictions to [0,1]\n            \n            -   Effect modification on the odds ratio scale may be less common than on the probability scale\n    \n    -   Statistical basis\n    \n        -   The mean-variance relationship for binary data is naturally incorporated in the logistic regression likelihood\n            \n            -   Classical logistic regression accounts for heteroskedasticity through the binomial variance structure\n            \n            -   Can still use robust SEs if you want to relax distributional assumptions\n            \n### Reasons to use logistic regression\n\n-   First (scientific) reason: Case-Control Studies\n\n    -   Studying a rare disease, so we do study in reverse\n\n        -   e.g. find subjects with cancer (and suitable controls) and then ascertain exposure of interest\n\n        -   Estimate distribution of the \"effect\" across groups defined by \"cause\"\n\n        -   Proportion (or odds) of smokers among people with or without lung cancer\n\n    |            |               |               |\n    |------------|---------------|---------------|\n    |            | Lung Cancer + | Lung Cancer - |\n    | Smoker     | a             | b             |\n    | Non-Smoker | c             | d             |\n\n    : Case-Control or Cohort 2x2 Table. In the Case-Control design, the total number of subjects with Cancer $(a+c)$ and without cancer $(b+d)$ are fixed by design.\n\n    -   In contrast, a cohort study samples by exposure (smoking) and then estimates the distribution of the effect in exposure groups\n\n    -   In a case-control study, we cannot estimate prevalence (without knowing selection probabilities)\n\n        -   e.g. if doing a 1:1 case-control study, $(a+c) = b+d$ so it would look like $50\\%$ of the subjects have cancer\n\n    -   Odds ratios are estimable in either case-control or cohort sampling scheme\n\n        -   Cohort study: Odds of cancer among smoker compared to odds of cancer among nonsmokers\n\n        -   Case-control study: Odds of smoking among cancer compared to odds of smoking among non-cancer\n\n    -   Mathematically, these two odds ratios are the same\n\n$$\\text{OR}_{\\text{cohort}} = \\frac{\\text{Odds of disease in exposed}}{\\text{Odds of disease in unexposed}} = \\frac{P(D=1|E=1)/P(D=0|E=1)}{P(D=1|E=0)/P(D=0|E=0)}$$\n\n$$= \\frac{P(D=1|E=1) \\times P(D=0|E=0)}{P(D=0|E=1) \\times P(D=1|E=0)}$$\n\n$$\\text{OR}_{\\text{case-control}} = \\frac{\\text{Odds of exposure in diseased}}{\\text{Odds of exposure in non-diseased}} = \\frac{P(E=1|D=1)/P(E=0|D=1)}{P(E=1|D=0)/P(E=0|D=0)}$$\n\n$$= \\frac{P(E=1|D=1) \\times P(E=0|D=0)}{P(E=0|D=1) \\times P(E=1|D=0)}$$\n\nBy Bayes' theorem, $P(D=1|E=1) = \\frac{P(E=1|D=1) \\times P(D=1)}{P(E=1)}$, and similarly for the other conditional probabilities. Substituting these into the cohort odds ratio:\n\n$$\\text{OR}_{\\text{cohort}} = \\frac{\\frac{P(E=1|D=1) \\times P(D=1)}{P(E=1)} \\times \\frac{P(E=0|D=0) \\times P(D=0)}{P(E=0)}}{\\frac{P(E=0|D=1) \\times P(D=1)}{P(E=0)} \\times \\frac{P(E=1|D=0) \\times P(D=0)}{P(E=1)}}$$\n\n$$= \\frac{P(E=1|D=1) \\times P(E=0|D=0)}{P(E=0|D=1) \\times P(E=1|D=0)} = \\text{OR}_{\\text{case-control}}$$\n\n- Thus, the disease odds ratio equals the exposure odds ratio, making the odds ratio estimable from either study design.\n\n\n    -   Odds ratios are easy to interpret when investigating rare events\n\n        -   Odds = prob / (1 - prob)\n\n        -   For rare events, (1 - prob) is approximately 1\n\n            -   Odds is approximately the probability\n\n            -   Odds ratios are approximately risk ratios\n\n        -   Case-control studies usually used when events are rare\n\n-   Second (scientific) reason: Linearity\n\n    -   Proportions are bounded by 0 and 1\n\n    -   It is thus unlikely that a straight line relationship would exists between a proportion and a predictor\n\n        -   Unless the predictor itself is bounded\n\n        -   Otherwise, there eventually must be a threshold above which the probability does not increase (or only increases a little)\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nexpit <- function(x) {exp(x)/(1+exp(x))}\nplot(function(x) expit(x), -4,4, ylab=\"Probabilty\", xlab=\"Predictor\")\n```\n\n::: {.cell-output-display}\n![Logistic function will bound probabilities between 0 and 1](Lec04.Logistic_files/figure-html/unnamed-chunk-2-1.png){width=672}\n:::\n:::\n\n\n\n\n-   Third (scientific) reason: Effect modification\n\n    -   The restriction on ranges for probabilities makes it likely that effect modification *must* be present with proportions\n\n    -   Example: Is the association between 2-year relapse rates and having a positive scan modified by gender?\n\n        -   Women relapse 40% of the time when the scan is negative, and 95% of the time when the scan is positive (an increase of 55%)\n\n            -   If men relapse 75% of the time when the scan is negative, then a positive scan can increase the relapse rate to at most 100%, which is only a 25% increase\n\n                |                 |       |              |\n                |-----------------|-------|--------------|\n                | **Proportions** |       |              |\n                |                 | Women | Men          |\n                | Negative Scan   | 40%   | 75%          |\n                | Positive Scan   | 95%   | (up to 100%) |\n                |                 |       |              |\n                | Difference      | 55%   | Up to 25%    |\n                | Ratio           | 2.38  | $\\leq 1.33$  |\n\n            -   With the odds, the association can hold without effect modification\n\n                |               |       |                  |\n                |---------------|-------|------------------|\n                | **Odds**      |       |                  |\n                |               | Women | Men              |\n                | Negative Scan | 0.67  | 3                |\n                | Positive Scan | 19    | (up to $\\infty$) |\n                |               |       |                  |\n                | Ratio         | 28.5  | $< \\infty$       |\n\n-   If the odds of positive scan in men was 85.5, then the odds ratio would be exactly 28.5 (no effect modification)\n\n-   Fourth (statistics) reason:\n\n    -   Classical linear regression requires equal variances across each predictor group\n\n    -   But, with binary data, the variance within a group depends on the mean\n\n    -   For binary $Y$, $E(Y) = p$ and $Var(Y) = p(1-p)$\n\n    -   With robust standard errors, the mean-variance relationship is not a major problem. However, a logistic model that correctly models the mean-variance relationship will be more efficient.\n\n### The simple logistic regression model\n\n-   Modeling the odds of binary response variable $Y$ on predictor $X$\n\n    -   Distribution: $\\textrm{Pr}(Y_i = 1) = p_i$\n\n    -   Model: $\\textrm{logit}(p_i) = \\textrm{log}\\left(\\frac{p_i}{1-p_i}\\right) = \\beta_0 + \\beta_1 \\times X_i$\n\n    -   When $X_i = 0$: log odds = $\\beta_0$\n\n    -   When $X_i = x$: log odds = $\\beta_0 + \\beta_1 \\times x$\n\n    -   When $X_i = x+1$: log odds = $\\beta_0 + \\beta_1 \\times x + \\beta_1$\n\n-   To interpret as odds, exponentiate the regression parameters\n\n    -   Distribution: $\\textrm{Pr}(Y_i = 1) = p_i$\n    -   Model: $\\frac{p_i}{1-p_i} = \\exp(\\beta_0 + \\beta_1 \\times X_i) = e^{\\beta_0} \\times e^{\\beta_1 \\times X_i}$\n    -   When $X_i = 0$: odds = $e^{\\beta_0}$\n    -   When $X_i = x$: odds = $e^{\\beta_0} \\times e^{\\beta_1 \\times x}$\n    -   When $X_i = x+1$: odds = $e^{\\beta_0} \\times e^{\\beta_1 \\times x} \\times e^{\\beta_1}$\n\n-   To interpret as proportions (remember proportion = odds / (1 + odds))\n\n    -   Distribution: $\\textrm{Pr}(Y_i = 1) = p_i$\n    -   Model: $p_i = \\frac{e^{\\beta_0} e^{\\beta_1 \\times X_i}}{1 + e^{\\beta_0} e^{\\beta_1 \\times X_i}}$\n    -   When $X_i = 0$: $p_i = \\frac{e^{\\beta_0}}{1 + e^{\\beta_0}}$\\\n    -   When $X_i = x$: $p_i = \\frac{e^{\\beta_0} e^{\\beta_1 \\times x}}{1 + e^{\\beta_0} e^{\\beta_1 \\times x}}$\n    -   When $X_i = x+1$: $p_i = \\frac{e^{\\beta_0} e^{\\beta_1 \\times x} e^{\\beta_1}}{1 + e^{\\beta_0} e^{\\beta_1 \\times x}e^{\\beta_1}}$\n\n-   Most common interpretations found by exponentiating the coefficients\n\n    -   Odds when predictor is 0 found by exponentiating the intercept: $\\exp(\\beta_0)$\n\n    -   Odds ratio between groups differing in the values of the predictor by 1 unit found by exponentiating the slope: $\\exp(\\beta_1)$\n\n-   Stata commands\n\n    ``` stata\n    logit respvar predvar, [robust]\n    ```\n\n    -   Provides regression parameter estimates an inference on the log odds scale (both coefficients with CIs, SEs, p-values)\n\n    ``` stata\n    logistic respvar predvar, [robust]\n    ```\n\n    -   Provides regression parameter estimates and inference on the odds ratio scale (only slope with CIs, SEs, p-values)\n\n-   R Commands\n\n    -   With rms package, `lrm(respvar ~ predvar, ...)`\n    \n       - `robcov(fit)` gives robust standard error estimates in `lrm'\n\n    -   In general, `glm(respvar ~ predvar, family=“binomial”)`\n    \n       - `sandwich()` in the sandwich library can give robust standard errors when using `glm`\n    \n\n## Example: Survival on the Titanic and Age\n\n-   Dataset at <https://statcomp2.app.vumc.org/modern-regression/lectures/data/>\n\n-   Describes the survival status of individual passengers on the Titanic\n\n-   Data on age available for many, but not all, subjects (data continually being updated)\n\n-   Response variables is Survival\n\n    -   Binary variable: 1=Survived, 0=Died\n\n-   Predictor variable is Age\n\n    -   Continuous grouping variable\n\n-   Possibly different age effects by sex (effect modification by sex)\n\n### Descriptive Plots\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(rms)\nlibrary(ggplot2)\ntitanic <- read.csv(file=\"data/titanic3.csv\")\nplot(naclus(titanic)) # study patterns of missing values\n```\n\n::: {.cell-output-display}\n![Missing data patterns in the Tianic dataset](Lec04.Logistic_files/figure-html/unnamed-chunk-3-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(titanic, aes(x=age, y=survived)) + geom_jitter(width=0, height=.02, alpha=.5) + geom_smooth()\n```\n\n::: {.cell-output-display}\n![Scatterplot of age versus survival in the Titanic data with lowess smooth.  This simple plot is not very useful because survival is either 0 or 1, making it hard to visualize any trends.](Lec04.Logistic_files/figure-html/unnamed-chunk-4-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nwith(titanic, \n     plsmo(age, survived, group=sex, datadensity=T, ylab=\"Survived (1=Yes, 0=No)\", xlab=\"Age (years)\")\n)\n```\n\n::: {.cell-output-display}\n![Age versus survival by sex in the Titanic data by age using a super smoother.  The trends are clearer with this smoothing approach.](Lec04.Logistic_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n:::\n\n\n\n\n-   Comments on the plots\n\n    -   Age is missing for many subjects, which we will not worry about in the following analysis\n\n    -   The simple scatterplot, even with superimposes lowess smooth, is worthless. I have jittered the point and altered their opacity to help visualize overlapping point.\n\n    -   More advanced plotting available in R (in this case, the plsmo() function) can help to visualize the data\n\n### Regression Model\n\n-   Regression model for survival on age (ignoring possible effect modification for now)\n\n-   Answer question by assessing linear trends in log odds of survival by age\n\n-   Estimate the best fitting line to log odds of survival within age groups\n\n$$\\textrm{logodds}(\\textrm{Survival} | \\textrm{Age}) = \\beta_0 + \\beta_1 \\times \\textrm{Age}$$\n\n-   An association will exist if the slope $\\beta_1$ is nonzero\n\n-   In that case, the odds (and probability) of survival will be different across different age groups\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm.titanic <- glm(survived ~ age, data=titanic, family = \"binomial\")\nsummary(m.titanic)\n```\n\n::: {.cell-output-display}\n\n-----------------------------------------------------------------\n     &nbsp;         Estimate    Std. Error   z value    Pr(>|z|) \n----------------- ------------ ------------ ---------- ----------\n **(Intercept)**   -0.1365340   0.1447153    -0.94347   0.345443 \n\n     **age**       -0.0078985   0.0044065    -1.79246   0.073059 \n-----------------------------------------------------------------\n\n\n(Dispersion parameter for  binomial  family taken to be  1 )\n\n\n-------------------- --------------------\n   Null deviance:      1414.6  on 1045   \n                      degrees of freedom \n\n Residual deviance:    1411.4  on 1044   \n                      degrees of freedom \n-------------------- --------------------\n\n  (263 observations deleted due to missingness)\n\nAIC: 1415.38\n\nNumber of Fisher Scoring Iterations: 4\n:::\n:::\n\n\n\n\n$\\textrm{logodds}(\\textrm{Survival} | \\textrm{Age}) = -0.1365 - 0.007899 \\times \\textrm{Age}$\n\n-   General interpretation\n\n    -   Intercept is labeled \"(Intercept)\"\n\n    -   Slope for age is labeled \"age\"\n\n-   Interpretation of intercept\n\n    \\*Estimated log odds for newborns (age=0) is $-0.136534$\n\n    -   Odds of survival for newborns is $e^{-0.136534} = 0.8724$\n\n    -   Probability of survival\n\n        -   Prob = odds / (1 + odds)\n\n        -   $0.8724 / (1 + .8724) = 0.4659$\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npredict(m.titanic, newdata=data.frame(age=0), type='response')\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        1 \n0.4659194 \n```\n\n\n:::\n:::\n\n\n\n\n-   Interpretation of slope\n\n    -   Estimate difference in the log odds of survival for two groups differing by one year in age is $-0.0078985$\n\n    -   This estimate averages over males and females\n\n    -   Older groups tend to have lower log odds\n\n    -   Odds Ratio: $e^{-0.0078985} = 0.9921$\n\n    -   For five year difference in age: $e^{-0.0078985 \\times 5} = 0.9612$\n\n    -   In Stata use \"lincom age, or\" or \"lincom 5\\*age, or\"\n\nNote that if the straight line relationship does not hold true, we interpret the slope as an average difference in the log odds of survival per one year difference in age\n\nThere are several ways to get the odds ratio and confidence interval in R\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# The coefficient and confidence interval (on the log-odds scale)\ncoef(m.titanic)[\"age\"]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         age \n-0.007898504 \n```\n\n\n:::\n\n```{.r .cell-code}\nconfint.default(m.titanic, \"age\")\n```\n\n::: {.cell-output-display}\n\n----------------------------------\n &nbsp;      2.5 %       97.5 %   \n--------- ----------- ------------\n **age**   -0.016535   0.00073809 \n----------------------------------\n\n\n:::\n\n```{.r .cell-code}\n# Odds ratio for age and confidence interval for age (1 year increase)\nexp(coef(m.titanic)[\"age\"])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      age \n0.9921326 \n```\n\n\n:::\n\n```{.r .cell-code}\nexp(confint.default(m.titanic, \"age\"))\n```\n\n::: {.cell-output-display}\n\n---------------------------\n &nbsp;    2.5 %    97.5 % \n--------- -------- --------\n **age**   0.9836   1.0007 \n---------------------------\n\n\n:::\n\n```{.r .cell-code}\n# Odds ratio for age and confidence interval for age (5 year increase)\nexp(5*coef(m.titanic)[\"age\"])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      age \n0.9612771 \n```\n\n\n:::\n\n```{.r .cell-code}\nexp(5*confint.default(m.titanic, \"age\"))\n```\n\n::: {.cell-output-display}\n\n----------------------------\n &nbsp;     2.5 %    97.5 % \n--------- --------- --------\n **age**   0.92065   1.0037 \n----------------------------\n\n\n:::\n:::\n\n\n\n\n-   Using finalfit to create a nicer output table of the coefficients and confidence intervals\n\n    -   For finalfit to use a logistic regression model by default, survived must be defined as a factor variable with two levels\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(finalfit)\nlibrary(rms)\nexplanatory = c(\"age\")\n\ntitanic$survived.factor <- factor(titanic$survived, levels=0:1, labels=c(\"Died\",\"Survived\"))\ndependent = 'survived.factor'\n\nlabel(titanic$age) <- \"Age (years)\"\nfinalfit(.data = titanic, dependent, explanatory)\n```\n\n::: {.cell-output-display}\n\n-------------------------------------------------------------------------------------------------\n   Dependent:                     Died        Survived     OR (univariable)   OR (multivariable) \n survived.factor                                                                                 \n----------------- ----------- ------------- ------------- ------------------ --------------------\n   Age (years)     Mean (SD)   30.5 (13.9)   28.9 (15.1)   0.99 (0.98-1.00,    0.99 (0.98-1.00,  \n                                                               p=0.073)            p=0.073)      \n-------------------------------------------------------------------------------------------------\n\n\n:::\n:::\n\n\n\n\n### Comments on Interpretation\n\n-   The slope for age is expressed as a difference in group means, not the difference due to aging. We did not do a longitudinal study in which repeated measurements were taken on the same subject.\n\n-   If the group log odds are truly linear, then the slope has an exact interpretation as the change in survival due to a one year change in (any) age\n\n-   Otherwise, the slope estimates the first order trend of the sample data and we should not treat the estimates of group odds or probabilities as accurate\n\n-   It is difficult to see in the above example, but the CIs around the odds ratios are not symmetric\n\n    -   (Symmetric) CIs are calculated on the log odds scale, and then transformed to the odds scale by expoenentiating the lower and upper limits of the CI\n\n-   \"From logistic regression analysis, we estimate that for each 5 year difference in age, the odds of survival on the Titanic decreased by 3.9%, though this estimate is not statistically significant ($p = 0.07$). A 95% CI suggests that this observation is not unusual if a group that is five years older might have an odds of survival that was anywhere between 7.9% lower and 0.4% higher than the younger group.\"\n\n-   The confidence interval and statistical test given in the output is called a Wald test. Other tests (Score, Likelihood Ratio) are also possible.\n\n    -   All tests are asymptotically equivalent\n\n    -   The Wald test is easiest to obtain, but generally performs the poorest in small sample sizes\n\n    -   The Likelihood Ratio test performs the best in small samples. We will discuss it later, including how to obtain the test using post-estimation commands.\n\n    -   The Score test is not bad in small samples, but is often hard to obtain from software. It is exactly equal to the Chi-squared test for binary outcomes and categorical predictors.\n\n#### Bayesian Estimates and Interpretation {#sec-bayeslogistic}\n\n-   Bayesian approach to the logistic model requires specifying the model, prior distributions, and the likelihood\n\n-   The model\n\n    -   e.g. a model for the log odds of survival that is linear in the parameters with an intercept and slope for age\n\n-   Prior distributions on parameters\n\n    -   For the simple logistic regression model, we have parameters $\\beta_0$, and $\\beta_1$.\n\n    -   For now, we will use default prior distributions that are are intended to be *weakly informative* in that they provide moderate regularization and help stabilize computation. See the [STAN documentation](https://mc-stan.org/rstanarm/reference/priors.html) for more details\n\n    -   Appropriate priors can be based on scientific considerations\n\n    -   Sensitivity analyses can evaluate the the robustness of finding to different prior assumptions\n\n-   The likelihood\n\n    -   For a binomial GLM the likelihood for one observation $y$ can be written as a conditionally binomial probability mass function\n\n$$\\binom{n}{y} \\pi^{y} (1 - \\pi)^{n - y},$$\n\n-   $n$ is the known number of trials, $\\pi = g^{-1}(\\eta)$ is the probability of success and $\\eta = \\alpha + \\mathbf{x}^\\top \\boldsymbol{\\beta}$ is a linear predictor\n\n<!-- -->\n\n-   For a sample of size $N$, the likelihood of the entire sample is the product of $N$ individual likelihood contributions.\n\n<!-- -->\n\n-   Because $\\pi$ is a probability, for a binomial model the *link* function $g$ maps between the unit interval (the support of $\\pi$) and the set of all real numbers $\\mathbb{R}$. When applied to a linear predictor $\\eta$ with values in $\\mathbb{R}$, the inverse link function $g^{-1}(\\eta)$ therefore returns a valid probability between 0 and 1.\n\n-   The two most common link functions used for binomial GLMs are the\n\n    -   [logit](https://en.wikipedia.org/wiki/Logit) and\n    -   [probit](https://en.wikipedia.org/wiki/Probit)\n\n-   With the logit (or log-odds) link function $g(x) = \\ln{\\left(\\frac{x}{1-x}\\right)}$, the likelihood for a single observation becomes\n\n$$\\binom{n}{y}\\left(\\text{logit}^{-1}(\\eta)\\right)^y \n\\left(1 - \\text{logit}^{-1}(\\eta)\\right)^{n-y} = \n\\binom{n}{y} \\left(\\frac{e^{\\eta}}{1 + e^{\\eta}}\\right)^{y}\n\\left(\\frac{1}{1 + e^{\\eta}}\\right)^{n - y}$$\n\n-   With the probit link function $g(x) = \\Phi^{-1}(x)$ yields the likelihood\n\n$$\\binom{n}{y} \\left(\\Phi(\\eta)\\right)^{y}\n\\left(1 - \\Phi(\\eta)\\right)^{n - y},$$\n\nwhere $\\Phi$ is the CDF of the standard normal distribution.\n\n-   Output from Bayesian logistic regression using logit link function\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(rstanarm)\nlibrary(bayesplot)\n\nfit2 <- stan_glm(survived ~ age,\n                 data=titanic, family=binomial(),\n                 seed=1234,\n                 refresh=0)\nsummary(fit2, digits=4, prob=c(.025, .5, .975))\n```\n\n::: {.cell-output-display}\n\n-----------------------------------------------------------------------------------------------\n function        family           formula       algorithm   sample   observations   predictors \n---------- ------------------ ---------------- ----------- -------- -------------- ------------\n stan_glm   binomial [logit]   survived ~ age   sampling     4000        1046           2      \n-----------------------------------------------------------------------------------------------\n\nTable: Model Info\n\n\n-------------------------------------------------------------------------------\n     &nbsp;           mean         sd        2.5%         50%         97.5%    \n----------------- ------------ ---------- ----------- ------------ ------------\n **(Intercept)**   -0.1343122   0.145938   -0.413530   -0.1336335   0.15599526 \n\n     **age**       -0.0079361   0.004433   -0.016909   -0.0077841   0.00035338 \n-------------------------------------------------------------------------------\n\nTable: Estimates\n\n\n---------------------------------------------------------------\n    &nbsp;       mean       sd       2.5%      50%      97.5%  \n-------------- --------- --------- -------- --------- ---------\n **mean_PPD**   0.40887   0.02167   0.3652   0.40918   0.45124 \n---------------------------------------------------------------\n\nTable: Fit Diagnostics\n\n\nThe mean_ppd is the sample average posterior predictive distribution of the outcome variable.\n\n-----------------------------------------------\n      &nbsp;          mcse      Rhat     n_eff \n------------------- --------- --------- -------\n  **(Intercept)**    0.00290   0.99941   2533  \n\n      **age**        0.00009   0.99964   2570  \n\n   **mean_PPD**      0.00039   1.00042   3073  \n\n **log-posterior**   0.02844   1.00475   1340  \n-----------------------------------------------\n\nTable: MCMC diagnostics\n\n\nFor each parameter, mcse is Monte Carlo standard error, n_eff is a crude measure of effective sample size, and Rhat is the potential scale reduction factor on split chains  (at convergence Rhat=1).\n\n\n:::\n:::\n\n\n\n\n-   And a summary of the prior distributions used\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprior_summary(fit2, digits = 2)\n```\n\n::: {.cell-output-display}\n\n----------------------------------------------------------------\n       &nbsp;           Specified prior       Adjusted prior    \n-------------------- --------------------- ---------------------\n **Intercept (after   ~ normal(location =                       \n     predictors       0, scale = 2.50000)                       \n    centered)**                                                 \n\n  **Coefficients**    ~ normal(location =   ~ normal(location = \n                      0, scale = 2.50000)   0, scale = 0.17345) \n----------------------------------------------------------------\n\nTable: Priors for model 'fit2'\n\n\n:::\n:::\n\n\n\n\n-   Interpretation\n\n    -   Slope for age is of primary scientific importance\n\n    -   *A priori* we assume that no association between age and survival. Specifically, we assumed a Normal prior with location (mean) of 0 and scale (standard devation) of 0.17 for $\\beta_1$.\n\n    -   Conditional on the data, we estimate that for every 1 year increase in age, the log odds of decreases by -0.0079 (95% credible interval -0.0169 to 0.0004).\n\n    -   To obtain the posterior odds ratio and 95% credible intervals, some additional commands are needed\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# 1 year change in age\nexp(coef(fit2)[\"age\"]) # Posterior Odds Ratio\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      age \n0.9922461 \n```\n\n\n:::\n\n```{.r .cell-code}\nexp(posterior_interval(fit2, prob = 0.95)) # 95% credible interval\n```\n\n::: {.cell-output-display}\n\n------------------------------------\n     &nbsp;         2.5%     97.5%  \n----------------- --------- --------\n **(Intercept)**   0.66131   1.1688 \n\n     **age**       0.98323   1.0004 \n------------------------------------\n\n\n:::\n\n```{.r .cell-code}\n# 5 year increase in age\nexp(5*coef(fit2)[\"age\"]) # Posterior Odds Ratio\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      age \n0.9618272 \n```\n\n\n:::\n\n```{.r .cell-code}\nexp(5*posterior_interval(fit2, prob = 0.95))[2,] # 95% credible interval\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     2.5%     97.5% \n0.9189294 1.0017684 \n```\n\n\n:::\n\n```{.r .cell-code}\n# Could also flip (invert) these odds ratios to interpret as decrease in age being associated with increased survival\n# 5 year decrease in age\n1/exp(5*coef(fit2)[\"age\"]) # Posterior Odds Ratio\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     age \n1.039688 \n```\n\n\n:::\n\n```{.r .cell-code}\n1/exp(5*posterior_interval(fit2, prob = 0.95))[2,] # 95% credible interval\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     2.5%     97.5% \n1.0882228 0.9982347 \n```\n\n\n:::\n:::\n\n\n\n\n-   The association between age and probability of survival was estimated using a Bayesian logistic regression model. The model did not adjust for other covariates and assumed a logit link function and Binomial likelihood. We assumed a weakly informative prior distribution for the log odds of survival given age (Normal prior with mean 0 and scale 0.17 for $\\beta_1$). Conditional on the data, the posterior mean estimate indicates that comparing two subjects who differ in age by 5 years, the younger subject has a 1.04 fold increased odds of survival compared to the older subject. A 95% credible interval for this posterior odds ratio is from 1.00 to 1.09.\n\n-   Note that this model does not consider gender, so it is averaging over the males and females. We will revisit this analysis where the age effect is analyzed separately in males and females.\n\n## Inference with Logistic Regression\n\n-   As with linear regression, we organize the assumptions needed for valid inference into categories based on what type of inference we wish to make\n\n    -   The structure of these assumptions parallels those discussed for linear regression, though the specifics differ due to the binary nature of the outcome\n\n-   The ideas of Signal and Noise found in simple linear regression do not translate well to logistic regression because of the implicit mean-variance relationship\n\n    -   We do not tend to quantify an error distribution with logistic regression\n\n-   Valid statistical inference (CIs, p-values) about *associations* requires three general assumptions\n\n-   Assumption 1: Approximately Normal distributions for the parameter estimates\n\n    -   Large N\n\n    -   Need for either robust standard errors or classical logistic regression\n\n    -   Definition of large depends on the underlying probabilities (odds)\n\n    -   Recall the rule of thumb for chi-squared tests based on the expected number of events\n\n-   Assumption 2: Assumptions about the independence of observations\n\n    -   Classical regression: Independence of all observation\n\n    -   Robust standard errors: Correlated observations within identified clusters\n\n-   Assumption 3: Assumptions about variance of observations within groups\n\n    -   Classical regression: Mean-variance relationship for binary data\n\n        -   Classical logistic regression estimates SE using model based estimates\n\n        -   Hence in order to satisfy this requirement, linearity of log odds across groups must hold\n\n    -   Robust standard errors\n\n        -   Allows unequal variance across groups\n\n        -   Hence, do not need linearity of log odds across groups to hold\n\n-   Valid statistical inference (CIs, p-values) about *odds of response in specific groups* requires a further assumption\n\n-   Assumption 4: Adequacy of the linear model\n\n    -   If we are trying to borrow information about the log odds from neighboring groups, and we are assuming a straight line relationship, the straight line needs to be true\n\n        -   Needed for either classical or robust standard errors\n\n        -   Note that we can model transformations of the measured predictor if we feel a straight line is not appropriate\n\n-   For inference about *individual observations* (prediction intervals, P-values) in specific groups requires no further assumptions because we have binary data\n\n    -   For binary data, if we know the mean (proportion), we know everything about the distribution including the variance\n    \n    -   This differs from linear regression where we needed Assumption 5 about the error distribution.\n    \n    -   With binary outcomes, once we correctly specify the mean (Assumption 4), the variance is automatically determined: $\\text{Var}(Y|X) = p(X)(1-p(X))$\n    \n    \n### Interpreting \"Positive\" Results\n\n-   Slope is statistically different from 0 using robust standard errors\n\n-   Observed data is atypical of a setting with no linear trend in odds of response across groups\n\n-   Data suggests evidence of a trend toward larger (or smaller) odds in groups having larger values of the predictor\n\n-   (To the extent the data appears linear, estimates of the group odds or probabilities will be reliable)\n\n### Interpreting \"Negative\" Results\n\n-   Many possible reasons why the slope is not statistically different from 0 using robust standard errors\n\n    -   There may be no association between the response and predictor\n\n    -   There may be an association in the parameter considered, but the best fitting line has zero slope\n\n    -   There may be a first order trend in the log odds, but we lacked the precision to be confident that it truly exists (a type II error)\n    \n    \n## Model Diagnostics for Understanding Results\n\n-   As with linear regression, diagnostics are tools for understanding the model and results, not for data-driven model modification\n\n-   Key differences from linear regression diagnostics\n\n    -   With binary outcomes, traditional residual plots are less informative\n    \n    -   Individual residuals are not very meaningful (outcome is always 0 or 1)\n    \n    -   Binned residuals can help visualize model fit\n\n-   Useful diagnostics for understanding logistic regression models\n\n    -   Binned residual plots: Group observations by predicted probability and examine average residuals within bins\n    \n    -   Influence diagnostics: Identify observations that have large impact on parameter estimates\n    \n    -   Predicted probabilities: Plot predicted probabilities across range of predictor to see if model behavior is sensible\n\n-   The goal remains understanding whether the model assumptions are plausible and whether results are sensitive to specific observations\n\n    -   Not to iteratively modify the model until diagnostics \"look good\"\n    \n    -   Pre-specification of the scientific model remains paramount\n\n### Diagnostic examples using Titanic data\n\n-   Recall our simple model of survival by age\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit.age <- glm(survived ~ age, data=titanic, family=\"binomial\")\nsummary(fit.age)\n```\n\n::: {.cell-output-display}\n\n-----------------------------------------------------------------\n     &nbsp;         Estimate    Std. Error   z value    Pr(>|z|) \n----------------- ------------ ------------ ---------- ----------\n **(Intercept)**   -0.1365340   0.1447153    -0.94347   0.345443 \n\n     **age**       -0.0078985   0.0044065    -1.79246   0.073059 \n-----------------------------------------------------------------\n\n\n(Dispersion parameter for  binomial  family taken to be  1 )\n\n\n-------------------- --------------------\n   Null deviance:      1414.6  on 1045   \n                      degrees of freedom \n\n Residual deviance:    1411.4  on 1044   \n                      degrees of freedom \n-------------------- --------------------\n\n  (263 observations deleted due to missingness)\n\nAIC: 1415.38\n\nNumber of Fisher Scoring Iterations: 4\n:::\n:::\n\n\n\n\n#### (Binned) residuals\n\n-   Binned residual plot\n\n    -   Groups observations into bins based on their predicted probabilities\n    \n    -   Within each bin, calculates the average residual (observed - predicted)\n    \n\n    -   If the model fits well, average residuals should be close to zero across all bins\n    \n    -   Gray lines show the expected 95% bounds (±2 SE) under the model\n    \n    -   Points outside these bounds suggest potential model misfit in those regions\n    \n    \n-   Why we need binned residuals for binary outcomes\n\n    -   With binary data, individual residuals are not very informative\n    \n    -   Each observation has $Y_i = 0$ or $Y_i = 1$, so residuals are either $0 - \\hat{p}_i$ or $1 - \\hat{p}_i$\n    \n    -   A plot of raw residuals shows two bands corresponding to the two possible outcomes\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create predicted probabilities and residuals for complete cases\npred_prob <- predict(fit.age, type=\"response\")\nresid <- titanic$survived[!is.na(titanic$age)] - pred_prob\n\n# Create data frame for plotting\nresid_data <- data.frame(pred_prob = pred_prob, resid = resid)\n\n# Plot raw (unbinned) residuals\nggplot(resid_data, aes(x = pred_prob, y = resid)) +\n  geom_point(alpha = 0.3) +\n  geom_hline(yintercept = 0, linetype = \"dashed\") +\n  labs(x = \"Predicted Probability\",\n       y = \"Raw Residual\",\n       title = \"Raw Residuals (Not Binned)\") +\n  theme_bw()\n```\n\n::: {.cell-output-display}\n![Raw residual plot (Titanic data)](Lec04.Logistic_files/figure-html/unnamed-chunk-15-1.png){width=672}\n:::\n:::\n\n\n\n\n-   The two bands in the plot correspond to survivors ($Y=1$, upper band) and non-survivors ($Y=0$, lower band)\n\n-   This plot provides little information about model fit - we cannot easily assess systematic deviations\n\n-   Binning the residuals by predicted probability allows us to see average deviations from the model\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(ggplot2)\n\n# Create predicted probabilities and residuals for complete cases\npred_prob <- predict(fit.age, type=\"response\")\nresid <- titanic$survived[!is.na(titanic$age)] - pred_prob\n\n# Create data frame for plotting\nresid_data <- data.frame(pred_prob = pred_prob, resid = resid)\n\n# Create bins for visualization\nn_bins <- 20\nbin_breaks <- seq(min(pred_prob), max(pred_prob), length.out = n_bins + 1)\nresid_data$bin <- cut(resid_data$pred_prob, breaks = bin_breaks)\n\n# Calculate binned statistics\nbinned_data <- aggregate(cbind(resid, pred_prob) ~ bin, \n                         data = resid_data, \n                         FUN = mean)\n\n# Create rectangles for shading alternating bins\nbin_rects <- data.frame(\n  xmin = bin_breaks[-length(bin_breaks)],\n  xmax = bin_breaks[-1],\n  shade = rep(c(TRUE, FALSE), length.out = n_bins)\n)\n\n# Plot raw residuals with shaded bins\nggplot(resid_data, aes(x = pred_prob, y = resid)) +\n  # Add shaded rectangles for alternating bins\n  geom_rect(data = bin_rects[bin_rects$shade, ], \n            aes(xmin = xmin, xmax = xmax, ymin = -Inf, ymax = Inf),\n            fill = \"lightblue\", alpha = 0.3, inherit.aes = FALSE) +\n  # Raw residuals\n  geom_point(alpha = 0.3) +\n  geom_hline(yintercept = 0, linetype = \"dashed\") +\n  # Add vertical lines to show bin boundaries\n  geom_vline(xintercept = bin_breaks,\n             color = \"blue\", alpha = 0.5, linetype = \"dotted\") +\n  # Add average residual within each bin\n  geom_point(data = binned_data, aes(x = pred_prob, y = resid),\n             color = \"red\", size = 3) +\n  geom_line(data = binned_data, aes(x = pred_prob, y = resid),\n            color = \"red\", linewidth = 1) +\n  labs(x = \"Predicted Probability\",\n       y = \"Raw Residual\") +\n  theme_bw()\n```\n\n::: {.cell-output-display}\n![Raw residuals from the logistic regression model of survival by age in the Titanic data. Individual residuals (gray points) form two bands corresponding to survivors (upper) and non-survivors (lower). Vertical boundaries divide predictions into 20 bins of equal width. Red points show the average residual within each bin, connected by a red line. This binning process, shown by the alternating shaded regions, transforms the uninformative raw residual plot into a more interpretable binned residual plot by averaging within prediction ranges.](Lec04.Logistic_files/figure-html/unnamed-chunk-16-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create predicted probabilities and residuals for complete cases\nn_bins <- 20\nresid_data$bin <- cut(resid_data$pred_prob, breaks = n_bins)\n\n# Calculate average residual and predicted probability within each bin\nbinned_data <- aggregate(cbind(resid, pred_prob) ~ bin, \n                         data = resid_data, \n                         FUN = mean)\nbinned_data$n <- table(resid_data$bin)\nbinned_data$se <- sqrt(binned_data$pred_prob * (1 - binned_data$pred_prob) / binned_data$n)\n\n# Plot binned residuals\nggplot(binned_data, aes(x = pred_prob, y = resid)) +\n  geom_point() +\n  geom_hline(yintercept = 0, linetype = \"dashed\") +\n  geom_ribbon(aes(ymin = -2*se, ymax = 2*se), alpha = 0.2) +\n  labs(x = \"Predicted Probability\",\n       y = \"Average Residual\",\n       title = \"Binned Residual Plot\") +\n  theme_bw()\n```\n\n::: {.cell-output-display}\n![Binned residual plot (Titanic data)](Lec04.Logistic_files/figure-html/unnamed-chunk-17-1.png){width=672}\n:::\n:::\n\n\n\n\n-   Interpretation of the binned residual plot\n\n    -   Most points fall within the gray bands, suggesting reasonable model fit\n    \n    -   Any systematic patterns (e.g., all positive residuals at low predictions, all negative at high predictions) would indicate the linear logit assumption may not hold\n    \n    -   Individual points outside the bands are not necessarily problematic - we expect about 5% of bins to fall outside\n    \n    -   Look for systematic deviations rather than isolated points\n    \n    -   In this example, the binned residuals show no strong systematic pattern, supporting the linear relationship between age and log odds of survival\n\n\n#### Predicted versus observed probabilities of survival\n\n\n-   Plot of predicted probabilities across age range\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create sequence of ages for model prediction\nage_seq <- seq(min(titanic$age, na.rm=TRUE), \n               max(titanic$age, na.rm=TRUE), \n               length.out=100)\n\n# Predict probabilities from model\npred_data <- data.frame(age = age_seq)\npred_data$prob <- predict(fit.age, newdata=pred_data, type=\"response\")\n\n# Plot\nggplot() +\n  # Raw data points\n  geom_point(data = titanic_complete, \n             aes(x = age, y = survived),\n             alpha = 0.2) +\n  # plsmo smoothed line\n  geom_line(data = smooth_data, \n            aes(x = age, y = prob, color = \"Observed (smoothed)\"),\n            linewidth = 1) +\n  # Model prediction line\n  geom_line(data = pred_data, \n            aes(x = age, y = prob, color = \"Model prediction\"),\n            linewidth = 1) +\n  scale_color_manual(values = c(\"Observed (smoothed)\" = \"black\", \n                                 \"Model prediction\" = \"blue\")) +\n  labs(x = \"Age (years)\",\n       y = \"Probability of Survival\",\n       color = NULL) +\n  ylim(0, 1) +\n  theme_bw() +\n  theme(legend.position = \"top\")\n```\n\n::: {.cell-output-display}\n![Predicted probability of survival versus age in the Titanic data. Gray points show individual observations (0 = died, 1 = survived). The black line shows a smoothed estimate of the observed survival probability using a super smoother. The blue line shows predictions from the logistic regression model assuming a linear relationship between age and log odds of survival. Close agreement between the two lines suggests the linear logit assumption is reasonable across the observed age range.](Lec04.Logistic_files/figure-html/unnamed-chunk-19-1.png){width=672}\n:::\n:::\n\n\n\n\n-   These plots help us understand how well the linear logit assumption fits the data and whether the model predictions are reasonable across the range of ages\n\n\n\n\n####   Influential observations using delta-betas\n\n-   Delta-beta measures the change in a parameter estimate when a single observation is removed from the analysis\n    \n-   For observation $i$ and parameter $\\beta_j$:\n\n   - $\\Delta\\beta_{ij} = \\hat{\\beta}_j - \\hat{\\beta}_{j(-i)}$\n    \n      - $\\hat{\\beta}_j$ is the estimate using all data\n        \n      - $\\hat{\\beta}_{j(-i)}$ is the estimate with observation $i$ removed\n    \n-   Large delta-betas indicate observations with substantial influence on parameter estimates\n    \n-   Delta-betas are a general concept applicable to any regression model (linear, logistic, Cox, etc.)\n    \n-   Can calculate delta-betas for any parameter of interest (intercept, slopes, interactions)\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculate delta-betas for the age coefficient\nn <- sum(!is.na(titanic$age))\ndelta_beta_age <- numeric(n)\n\n# Get full model coefficient\nbeta_full <- coef(fit.age)[\"age\"]\n\n# Calculate delta-beta for each observation\ntitanic_complete <- titanic[!is.na(titanic$age), ]\nfor(i in 1:n) {\n  fit_minus_i <- glm(survived ~ age, \n                     data=titanic_complete[-i, ], \n                     family=\"binomial\")\n  delta_beta_age[i] <- beta_full - coef(fit_minus_i)[\"age\"]\n}\n\n# Plot delta-betas\nplot(1:n, delta_beta_age, \n     xlab=\"Observation Number\", \n     ylab=\"Delta-Beta for Age Coefficient\",\n     main=\"Influence on Age Effect\",\n     pch=16, col=rgb(0,0,0,0.5))\nabline(h=0, lty=2)\n\n# Identify potentially influential observations\nthreshold <- 3*sd(delta_beta_age)\nabline(h=c(-threshold, threshold), lty=2, col=\"red\")\ninfluential <- which(abs(delta_beta_age) > threshold)\ntext(influential, delta_beta_age[influential], \n     labels=influential, pos=2, col=\"red\")\n```\n\n::: {.cell-output-display}\n![](Lec04.Logistic_files/figure-html/unnamed-chunk-20-1.png){width=672}\n:::\n:::\n\n\n\n\n-   Interpretation of delta-betas\n\n    -   Observations with large positive delta-betas increase the age coefficient estimate when included\n    \n    -   Observations with large negative delta-betas decrease the age coefficient estimate when included\n    \n    -   Influential observations are not necessarily \"bad\" or errors - they may represent legitimate extreme cases\n    \n    -   The goal is to understand which observations influence the results, not to automatically exclude influential points\n\n-   For brevity, identify and examine the most influential observation\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Identify observation with largest absolute delta-beta\nmax_influence_index <- which.max(abs(delta_beta_age))\nmax_delta_beta <- delta_beta_age[max_influence_index]\n\n# Fit model without this observation\nfit_minus_max <- glm(survived ~ age, \n                     data=titanic_complete[-max_influence_index, ], \n                     family=\"binomial\")\n\n# Show details and comparison\ncat(sprintf(\"Most influential observation:\n  Observation number: %d\n  Age: %.1f\n  Survived: %d\n  Delta-beta: %.6f\n\nAge coefficient (full model): %.6f\nAge coefficient (without observation %d): %.6f\nDifference (delta-beta): %.6f\n\",\nmax_influence_index,\ntitanic_complete$age[max_influence_index],\ntitanic_complete$survived[max_influence_index],\nmax_delta_beta,\ncoef(fit.age)[\"age\"],\nmax_influence_index,\ncoef(fit_minus_max)[\"age\"],\ncoef(fit.age)[\"age\"] - coef(fit_minus_max)[\"age\"]\n))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMost influential observation:\n  Observation number: 15\n  Age: 80.0\n  Survived: 1\n  Delta-beta: 0.000678\n\nAge coefficient (full model): -0.007899\nAge coefficient (without observation 15): -0.008577\nDifference (delta-beta): 0.000678\n```\n\n\n:::\n:::\n\n\n\n\n-   This explicitly shows how removing a single influential observation changes the age coefficient estimate\n\n   - Here, this is an old subject (80) who survived; the model predicts low survival probability at that age, so this point has a relatively strong influence on the age effect estimate.\n\n## Example analysis revisited: Effect Modification\n\n-   Recall in our Titanic example that the effect of age appeared to differ by sex\n\n    -   We ignored this difference earlier, so our estimated age effect was a (weighted) average of the age effect in males and the age effect in female\n\n    -   Here is the plot again describing the trends we see in survival by age and sex (using plsmo).\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwith(titanic, \n     plsmo(age, survived, group=sex, datadensity=T, ylab=\"Survived (1=Yes, 0=No)\", xlab=\"Age (years)\")\n)\n```\n\n::: {.cell-output-display}\n![Age versus survival by gender in the Titanic data by age using a super smoother.](Lec04.Logistic_files/figure-html/unnamed-chunk-22-1.png){width=672}\n:::\n:::\n\n\n\n\n-   We could describe the observed differences in two way, both being correct\n\n    -   Gender modifies the age effect\n\n        -   In males, the probability of survival decreased with age while in female the probability of survival increased with age\n        -   Emphasizes that the female age slope is positive while the male age slope is negative\n\n    -   Age modifies the gender effect\n\n        -   The survival rates of male and females were more similar at younger ages than older ages\n        -   Could specify the odds ratio of survival comparing females to males at specific ages\n\n### Stratified analysis by sex\n\n-   The log odds of survival in females\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit.titanic.female <- glm(survived ~ age, data=titanic, subset=sex==\"female\", family=\"binomial\")\nfit.titanic.female\n```\n\n::: {.cell-output-display}\n\n---------------------------------------------------------------\n     &nbsp;        Estimate   Std. Error   z value   Pr(>|z|)  \n----------------- ---------- ------------ --------- -----------\n **(Intercept)**   0.493374   0.2541885    1.9410    0.0522612 \n\n     **age**       0.022516   0.0085354    2.6379    0.0083415 \n---------------------------------------------------------------\n\nTable: Fitting generalized (binomial/logit) linear model: survived ~ age\n\n\n------------------- -----------------\n   **Degrees of      387 Total (i.e. \n     Freedom**            Null)      \n\n   **Degrees of       386 Residual   \n     Freedom**                       \n\n **Null Deviance**       434.161     \n\n    **Residual           426.878     \n    Deviance**                       \n\n      **AIC**            430.878     \n------------------- -----------------\n\n  (78 observations deleted due to missingness)\n\n\n:::\n:::\n\n\n\n\n-   The log odds of survival in males\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit.titanic.male <- glm(survived ~ age, data=titanic, subset=sex==\"male\", family=\"binomial\")\nfit.titanic.male\n```\n\n::: {.cell-output-display}\n\n---------------------------------------------------------------\n     &nbsp;        Estimate   Std. Error   z value   Pr(>|z|)  \n----------------- ---------- ------------ --------- -----------\n **(Intercept)**   -0.66076   0.2248071    -2.9392   0.0032902 \n\n     **age**       -0.02376   0.0072757    -3.2657   0.0010921 \n---------------------------------------------------------------\n\nTable: Fitting generalized (binomial/logit) linear model: survived ~ age\n\n\n------------------- -----------------\n   **Degrees of      657 Total (i.e. \n     Freedom**            Null)      \n\n   **Degrees of       656 Residual   \n     Freedom**                       \n\n **Null Deviance**       667.847     \n\n    **Residual           656.557     \n    Deviance**                       \n\n      **AIC**            660.557     \n------------------- -----------------\n\n  (185 observations deleted due to missingness)\n\n\n:::\n:::\n\n\n\n\n#### Odds ratios and confidence intervals for age effect by sex\n\n-   Consider a 5 year change in age\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Females\nexp(5*coef(fit.titanic.female)[\"age\"])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     age \n1.119161 \n```\n\n\n:::\n\n```{.r .cell-code}\nexp(5*confint.default(fit.titanic.female,\"age\"))\n```\n\n::: {.cell-output-display}\n\n---------------------------\n &nbsp;    2.5 %    97.5 % \n--------- -------- --------\n **age**   1.0294   1.2168 \n---------------------------\n\n\n:::\n\n```{.r .cell-code}\n# Males\nexp(5*coef(fit.titanic.male)[\"age\"])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      age \n0.8879858 \n```\n\n\n:::\n\n```{.r .cell-code}\nexp(5*confint.default(fit.titanic.male,\"age\"))\n```\n\n::: {.cell-output-display}\n\n-----------------------------\n &nbsp;     2.5 %    97.5 %  \n--------- --------- ---------\n **age**   0.82688   0.95361 \n-----------------------------\n\n\n:::\n:::\n\n\n\n\n### Effect modification using interaction terms\n\n-   Instead of fitting two separate models for male and females, we could estimate all parameters in a single regression model\n    -   Let $p_i$ be the probability of survival for passenger $i$ and $\\textrm{logit}(p)= \\textrm{log}\\left(\\frac{p}{1-p}\\right)$\n    -   Let $X_{1i}$ be the age of subject $i$\n    -   Let $X_{2i}$ be an indicator variable for female sex. $X_{2i}=1$ if a subject is female and $X_{2i} = 0$ if a subject is male\n\n$$\\textrm{logit}(p_i | X_{1i},X_{2i}) = \\beta_0 + \\beta_1 * X_{1i} + \\beta_{2} * X_{2i} + \\beta_3*X_{1i}*X_{2i}$$\n\n-   In males, $X_{2i} = 0$, this model reduces to\n\n$$\\textrm{logit}(p_i | X_{1i}, X_{2i}=0) = \\beta_0 + \\beta_1 * X_{1i}$$\n\n-   In females, $X_{2i} = 1$, this model can be expressed as\n\n$$\\textrm{logit}(p_i | X_{1i}, X_{2i}=1) = (\\beta_0+\\beta_2) + (\\beta_1+\\beta_3) * X_{1i}$$\n\n-   $\\hat{\\beta_1}$ is the estimate age effect in males\n-   $\\hat{\\beta_1} + \\hat{\\beta_3}$ is the estimated age effect in females\n-   $\\hat{\\beta_3}$ is the estimated *difference* between the age effect in females and the age effect in males\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# female has already been defined in the dataset, but if I wanted to create this variable I could do so\ntitanic$female <- (titanic$sex==\"female\")+0\n\nfit.titanic.interact <- glm(survived ~ age + female + age*female, data=titanic, family=\"binomial\")\nsummary(fit.titanic.interact)\n```\n\n::: {.cell-output-display}\n\n-----------------------------------------------------------------\n     &nbsp;        Estimate    Std. Error   z value    Pr(>|z|)  \n----------------- ----------- ------------ --------- ------------\n **(Intercept)**   -0.660761   0.2248071    -2.9392   3.2902e-03 \n\n     **age**       -0.023760   0.0072757    -3.2657   1.0921e-03 \n\n   **female**      1.154134    0.3393376    3.4011    6.7106e-04 \n\n **age:female**    0.046276    0.0112156    4.1260    3.6909e-05 \n-----------------------------------------------------------------\n\n\n(Dispersion parameter for  binomial  family taken to be  1 )\n\n\n-------------------- --------------------\n   Null deviance:      1414.6  on 1045   \n                      degrees of freedom \n\n Residual deviance:    1083.4  on 1042   \n                      degrees of freedom \n-------------------- --------------------\n\n  (263 observations deleted due to missingness)\n\nAIC: 1091.44\n\nNumber of Fisher Scoring Iterations: 4\n:::\n:::\n\n\n\n\n-   We can see that the parameter estimates from the interaction model are the same as the estimates from the two stratified models\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Interaction model\ncoef(fit.titanic.interact)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n(Intercept)         age      female  age:female \n-0.66076066 -0.02375991  1.15413441  0.04627571 \n```\n\n\n:::\n\n```{.r .cell-code}\n# Model fit just on male subjects\ncoef(fit.titanic.male)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n(Intercept)         age \n-0.66076066 -0.02375991 \n```\n\n\n:::\n\n```{.r .cell-code}\n# Model fit just on female subjects\ncoef(fit.titanic.female)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n(Intercept)         age \n 0.49337375  0.02251581 \n```\n\n\n:::\n\n```{.r .cell-code}\n# Linear combinations from the interaction model give the female intercept and age slope\ncoef(fit.titanic.interact)[1] + coef(fit.titanic.interact)[3]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n(Intercept) \n  0.4933738 \n```\n\n\n:::\n\n```{.r .cell-code}\ncoef(fit.titanic.interact)[2] + coef(fit.titanic.interact)[4]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       age \n0.02251581 \n```\n\n\n:::\n:::\n",
    "supporting": [
      "Lec04.Logistic_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}